package biz.freshcode.learn.gwt.client.uispike.builder.field;

import com.sencha.gxt.widget.core.client.form.FieldLabel;

// Generated by BeanBuilderGenerator
@biz.freshcode.learn.gwt.client.uispike.builder.BeanBuilder(FieldLabel.class)
public class FieldLabelBuilder {
    public final FieldLabel fieldLabel;

    public FieldLabelBuilder() {
        this(new FieldLabel());
    }

    public FieldLabelBuilder(FieldLabel v) {
        fieldLabel = v;
    }

    public FieldLabelBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        fieldLabel.add(v0);
        return this;
    }

    public FieldLabelBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        fieldLabel.add(v0);
        return this;
    }

    public FieldLabelBuilder add(com.google.gwt.user.client.ui.Widget v0, com.sencha.gxt.widget.core.client.container.MarginData v1) {
        fieldLabel.add(v0, v1);
        return this;
    }

    public FieldLabelBuilder addStyleDependentName(java.lang.String v0) {
        fieldLabel.addStyleDependentName(v0);
        return this;
    }

    public FieldLabelBuilder addStyleName(java.lang.String v0) {
        fieldLabel.addStyleName(v0);
        return this;
    }

    public FieldLabelBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        fieldLabel.addStyleOnOver(v0, v1);
        return this;
    }

    public FieldLabelBuilder allowTextSelection(boolean v0) {
        fieldLabel.setAllowTextSelection(v0);
        return this;
    }

    public FieldLabelBuilder borders(boolean v0) {
        fieldLabel.setBorders(v0);
        return this;
    }

    public FieldLabelBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        fieldLabel.setBounds(v0);
        return this;
    }

    public FieldLabelBuilder bounds(int v0, int v1, int v2, int v3) {
        fieldLabel.setBounds(v0, v1, v2, v3);
        return this;
    }

    public FieldLabelBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        fieldLabel.setContextMenu(v0);
        return this;
    }

    public FieldLabelBuilder data(java.lang.String v0, java.lang.Object v1) {
        fieldLabel.setData(v0, v1);
        return this;
    }

    public FieldLabelBuilder deferHeight(boolean v0) {
        fieldLabel.setDeferHeight(v0);
        return this;
    }

    public FieldLabelBuilder enabled(boolean v0) {
        fieldLabel.setEnabled(v0);
        return this;
    }

    public FieldLabelBuilder hTML(com.google.gwt.safehtml.shared.SafeHtml v0) {
        fieldLabel.setHTML(v0);
        return this;
    }

    public FieldLabelBuilder hTML(java.lang.String v0) {
        fieldLabel.setHTML(v0);
        return this;
    }

    public FieldLabelBuilder height(int v0) {
        fieldLabel.setHeight(v0);
        return this;
    }

    public FieldLabelBuilder height(java.lang.String v0) {
        fieldLabel.setHeight(v0);
        return this;
    }

    public FieldLabelBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        fieldLabel.setHideMode(v0);
        return this;
    }

    public FieldLabelBuilder id(java.lang.String v0) {
        fieldLabel.setId(v0);
        return this;
    }

    public FieldLabelBuilder itemId(java.lang.String v0) {
        fieldLabel.setItemId(v0);
        return this;
    }

    public FieldLabelBuilder labelAlign(com.sencha.gxt.widget.core.client.form.FormPanel.LabelAlign v0) {
        fieldLabel.setLabelAlign(v0);
        return this;
    }

    public FieldLabelBuilder labelPad(int v0) {
        fieldLabel.setLabelPad(v0);
        return this;
    }

    public FieldLabelBuilder labelSeparator(java.lang.String v0) {
        fieldLabel.setLabelSeparator(v0);
        return this;
    }

    public FieldLabelBuilder labelWidth(int v0) {
        fieldLabel.setLabelWidth(v0);
        return this;
    }

    public FieldLabelBuilder layoutData(java.lang.Object v0) {
        fieldLabel.setLayoutData(v0);
        return this;
    }

    public FieldLabelBuilder pagePosition(int v0, int v1) {
        fieldLabel.setPagePosition(v0, v1);
        return this;
    }

    public FieldLabelBuilder pixelSize(int v0, int v1) {
        fieldLabel.setPixelSize(v0, v1);
        return this;
    }

    public FieldLabelBuilder position(int v0, int v1) {
        fieldLabel.setPosition(v0, v1);
        return this;
    }

    public FieldLabelBuilder resize(boolean v0) {
        fieldLabel.setResize(v0);
        return this;
    }

    public FieldLabelBuilder shadow(boolean v0) {
        fieldLabel.setShadow(v0);
        return this;
    }

    public FieldLabelBuilder size(java.lang.String v0, java.lang.String v1) {
        fieldLabel.setSize(v0, v1);
        return this;
    }

    public FieldLabelBuilder stateId(java.lang.String v0) {
        fieldLabel.setStateId(v0);
        return this;
    }

    public FieldLabelBuilder stateful(boolean v0) {
        fieldLabel.setStateful(v0);
        return this;
    }

    public FieldLabelBuilder styleDependentName(java.lang.String v0, boolean v1) {
        fieldLabel.setStyleDependentName(v0, v1);
        return this;
    }

    public FieldLabelBuilder styleName(java.lang.String v0) {
        fieldLabel.setStyleName(v0);
        return this;
    }

    public FieldLabelBuilder styleName(java.lang.String v0, boolean v1) {
        fieldLabel.setStyleName(v0, v1);
        return this;
    }

    public FieldLabelBuilder stylePrimaryName(java.lang.String v0) {
        fieldLabel.setStylePrimaryName(v0);
        return this;
    }

    public FieldLabelBuilder tabIndex(int v0) {
        fieldLabel.setTabIndex(v0);
        return this;
    }

    public FieldLabelBuilder text(java.lang.String v0) {
        fieldLabel.setText(v0);
        return this;
    }

    public FieldLabelBuilder title(java.lang.String v0) {
        fieldLabel.setTitle(v0);
        return this;
    }

    public FieldLabelBuilder toolTip(java.lang.String v0) {
        fieldLabel.setToolTip(v0);
        return this;
    }

    public FieldLabelBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        fieldLabel.setToolTipConfig(v0);
        return this;
    }

    public FieldLabelBuilder visible(boolean v0) {
        fieldLabel.setVisible(v0);
        return this;
    }

    public FieldLabelBuilder widget(com.google.gwt.user.client.ui.Widget v0) {
        fieldLabel.setWidget(v0);
        return this;
    }

    public FieldLabelBuilder widget(com.google.gwt.user.client.ui.IsWidget v0) {
        fieldLabel.setWidget(v0);
        return this;
    }

    public FieldLabelBuilder width(int v0) {
        fieldLabel.setWidth(v0);
        return this;
    }

    public FieldLabelBuilder width(java.lang.String v0) {
        fieldLabel.setWidth(v0);
        return this;
    }
}
