package biz.freshcode.learn.gwt2.common.client.builder.gxt.grid;

import com.sencha.gxt.widget.core.client.grid.GroupSummaryView;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt2.common.client.builder.BeanBuilder(GroupSummaryView.class)
public class GroupSummaryViewBuilder<M> extends biz.freshcode.learn.gwt2.common.client.builder.Construct.Parent<GroupSummaryViewBuilder<M>> {
    public final GroupSummaryView<M> groupSummaryView;

    public GroupSummaryViewBuilder(GroupSummaryView<M> v) {
        groupSummaryView = v;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#GroupSummaryView()
     */
    public GroupSummaryViewBuilder() {
        this(new GroupSummaryView<M>());
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#GroupSummaryView(com.sencha.gxt.widget.core.client.grid.GroupSummaryView.GroupSummaryViewAppearance)
     */
    public GroupSummaryViewBuilder(com.sencha.gxt.widget.core.client.grid.GroupSummaryView.GroupSummaryViewAppearance v0) {
        this(new GroupSummaryView<M>(v0));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#GroupSummaryView(com.sencha.gxt.widget.core.client.grid.GridView.GridAppearance, com.sencha.gxt.widget.core.client.grid.GroupSummaryView.GroupSummaryViewAppearance)
     */
    public GroupSummaryViewBuilder(com.sencha.gxt.widget.core.client.grid.GridView.GridAppearance v0, com.sencha.gxt.widget.core.client.grid.GroupSummaryView.GroupSummaryViewAppearance v1) {
        this(new GroupSummaryView<M>(v0, v1));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setAdjustForHScroll(boolean)
     */
    public GroupSummaryViewBuilder<M> adjustForHScroll(boolean v0) {
        groupSummaryView.setAdjustForHScroll(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setAutoExpandColumn(com.sencha.gxt.widget.core.client.grid.ColumnConfig)
     */
    public GroupSummaryViewBuilder<M> autoExpandColumn(com.sencha.gxt.widget.core.client.grid.ColumnConfig<M, ?> v0) {
        groupSummaryView.setAutoExpandColumn(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setAutoExpandMax(int)
     */
    public GroupSummaryViewBuilder<M> autoExpandMax(int v0) {
        groupSummaryView.setAutoExpandMax(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setAutoExpandMin(int)
     */
    public GroupSummaryViewBuilder<M> autoExpandMin(int v0) {
        groupSummaryView.setAutoExpandMin(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setAutoFill(boolean)
     */
    public GroupSummaryViewBuilder<M> autoFill(boolean v0) {
        groupSummaryView.setAutoFill(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setColumnHeader(com.sencha.gxt.widget.core.client.grid.ColumnHeader)
     */
    public GroupSummaryViewBuilder<M> columnHeader(com.sencha.gxt.widget.core.client.grid.ColumnHeader<M> v0) {
        groupSummaryView.setColumnHeader(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setColumnLines(boolean)
     */
    public GroupSummaryViewBuilder<M> columnLines(boolean v0) {
        groupSummaryView.setColumnLines(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setDeferUpdates(boolean)
     */
    public GroupSummaryViewBuilder<M> deferUpdates(boolean v0) {
        groupSummaryView.setDeferUpdates(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setEmptyText(java.lang.String)
     */
    public GroupSummaryViewBuilder<M> emptyText(java.lang.String v0) {
        groupSummaryView.setEmptyText(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setEnableGroupingMenu(boolean)
     */
    public GroupSummaryViewBuilder<M> enableGroupingMenu(boolean v0) {
        groupSummaryView.setEnableGroupingMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setEnableNoGroups(boolean)
     */
    public GroupSummaryViewBuilder<M> enableNoGroups(boolean v0) {
        groupSummaryView.setEnableNoGroups(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setEnableRowBody(boolean)
     */
    public GroupSummaryViewBuilder<M> enableRowBody(boolean v0) {
        groupSummaryView.setEnableRowBody(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setForceFit(boolean)
     */
    public GroupSummaryViewBuilder<M> forceFit(boolean v0) {
        groupSummaryView.setForceFit(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setRowBodyRowSpan(int)
     */
    public GroupSummaryViewBuilder<M> rowBodyRowSpan(int v0) {
        groupSummaryView.setRowBodyRowSpan(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setShowDirtyCells(boolean)
     */
    public GroupSummaryViewBuilder<M> showDirtyCells(boolean v0) {
        groupSummaryView.setShowDirtyCells(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setShowGroupedColumn(boolean)
     */
    public GroupSummaryViewBuilder<M> showGroupedColumn(boolean v0) {
        groupSummaryView.setShowGroupedColumn(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setSortingEnabled(boolean)
     */
    public GroupSummaryViewBuilder<M> sortingEnabled(boolean v0) {
        groupSummaryView.setSortingEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setStartCollapsed(boolean)
     */
    public GroupSummaryViewBuilder<M> startCollapsed(boolean v0) {
        groupSummaryView.setStartCollapsed(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setStripeRows(boolean)
     */
    public GroupSummaryViewBuilder<M> stripeRows(boolean v0) {
        groupSummaryView.setStripeRows(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setTrackMouseOver(boolean)
     */
    public GroupSummaryViewBuilder<M> trackMouseOver(boolean v0) {
        groupSummaryView.setTrackMouseOver(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.grid.GroupSummaryView#setViewConfig(com.sencha.gxt.widget.core.client.grid.GridViewConfig)
     */
    public GroupSummaryViewBuilder<M> viewConfig(com.sencha.gxt.widget.core.client.grid.GridViewConfig<M> v0) {
        groupSummaryView.setViewConfig(v0);
        return this;
    }
}
