package biz.freshcode.learn.gwtp.client.builder.gxt.menu;

import com.sencha.gxt.widget.core.client.menu.MenuBarItem;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwtp.client.builder.BeanBuilder(MenuBarItem.class)
public class MenuBarItemBuilder extends biz.freshcode.learn.gwtp.client.builder.Construct.Parent<MenuBarItemBuilder> {
    public final MenuBarItem menuBarItem;

    public MenuBarItemBuilder(MenuBarItem v) {
        menuBarItem = v;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#MenuBarItem(java.lang.String, com.sencha.gxt.widget.core.client.menu.Menu, com.sencha.gxt.widget.core.client.menu.MenuBarItem.MenuBarItemAppearance)
     */
    public MenuBarItemBuilder(java.lang.String v0, com.sencha.gxt.widget.core.client.menu.Menu v1, com.sencha.gxt.widget.core.client.menu.MenuBarItem.MenuBarItemAppearance v2) {
        this(new MenuBarItem(v0, v1, v2));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#MenuBarItem(java.lang.String, com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public MenuBarItemBuilder(java.lang.String v0, com.sencha.gxt.widget.core.client.menu.Menu v1) {
        this(new MenuBarItem(v0, v1));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#MenuBarItem(java.lang.String)
     */
    public MenuBarItemBuilder(java.lang.String v0) {
        this(new MenuBarItem(v0));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#addStyleDependentName(java.lang.String)
     */
    public MenuBarItemBuilder addStyleDependentName(java.lang.String v0) {
        menuBarItem.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#addStyleName(java.lang.String)
     */
    public MenuBarItemBuilder addStyleName(java.lang.String v0) {
        menuBarItem.addStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#addStyleOnOver(com.google.gwt.dom.client.Element, java.lang.String)
     */
    public MenuBarItemBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        menuBarItem.addStyleOnOver(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setAllowTextSelection(boolean)
     */
    public MenuBarItemBuilder allowTextSelection(boolean v0) {
        menuBarItem.setAllowTextSelection(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setBorders(boolean)
     */
    public MenuBarItemBuilder borders(boolean v0) {
        menuBarItem.setBorders(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setBounds(com.sencha.gxt.core.client.util.Rectangle)
     */
    public MenuBarItemBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        menuBarItem.setBounds(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setBounds(int, int, int, int)
     */
    public MenuBarItemBuilder bounds(int v0, int v1, int v2, int v3) {
        menuBarItem.setBounds(v0, v1, v2, v3);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setContextMenu(com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public MenuBarItemBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        menuBarItem.setContextMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setData(java.lang.String, java.lang.Object)
     */
    public MenuBarItemBuilder data(java.lang.String v0, java.lang.Object v1) {
        menuBarItem.setData(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setDeferHeight(boolean)
     */
    public MenuBarItemBuilder deferHeight(boolean v0) {
        menuBarItem.setDeferHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setEnabled(boolean)
     */
    public MenuBarItemBuilder enabled(boolean v0) {
        menuBarItem.setEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setHTML(java.lang.String)
     */
    public MenuBarItemBuilder hTML(java.lang.String v0) {
        menuBarItem.setHTML(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setHeight(int)
     */
    public MenuBarItemBuilder height(int v0) {
        menuBarItem.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setHeight(java.lang.String)
     */
    public MenuBarItemBuilder height(java.lang.String v0) {
        menuBarItem.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setHideMode(com.sencha.gxt.core.client.Style.HideMode)
     */
    public MenuBarItemBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        menuBarItem.setHideMode(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setId(java.lang.String)
     */
    public MenuBarItemBuilder id(java.lang.String v0) {
        menuBarItem.setId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setItemId(java.lang.String)
     */
    public MenuBarItemBuilder itemId(java.lang.String v0) {
        menuBarItem.setItemId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setLayoutData(java.lang.Object)
     */
    public MenuBarItemBuilder layoutData(java.lang.Object v0) {
        menuBarItem.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setMenu(com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public MenuBarItemBuilder menu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        menuBarItem.setMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setPagePosition(int, int)
     */
    public MenuBarItemBuilder pagePosition(int v0, int v1) {
        menuBarItem.setPagePosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setPixelSize(int, int)
     */
    public MenuBarItemBuilder pixelSize(int v0, int v1) {
        menuBarItem.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setPosition(int, int)
     */
    public MenuBarItemBuilder position(int v0, int v1) {
        menuBarItem.setPosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setShadow(boolean)
     */
    public MenuBarItemBuilder shadow(boolean v0) {
        menuBarItem.setShadow(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setSize(java.lang.String, java.lang.String)
     */
    public MenuBarItemBuilder size(java.lang.String v0, java.lang.String v1) {
        menuBarItem.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setStateId(java.lang.String)
     */
    public MenuBarItemBuilder stateId(java.lang.String v0) {
        menuBarItem.setStateId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setStateful(boolean)
     */
    public MenuBarItemBuilder stateful(boolean v0) {
        menuBarItem.setStateful(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setStyleDependentName(java.lang.String, boolean)
     */
    public MenuBarItemBuilder styleDependentName(java.lang.String v0, boolean v1) {
        menuBarItem.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setStyleName(java.lang.String)
     */
    public MenuBarItemBuilder styleName(java.lang.String v0) {
        menuBarItem.setStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setStyleName(java.lang.String, boolean)
     */
    public MenuBarItemBuilder styleName(java.lang.String v0, boolean v1) {
        menuBarItem.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setStylePrimaryName(java.lang.String)
     */
    public MenuBarItemBuilder stylePrimaryName(java.lang.String v0) {
        menuBarItem.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setTabIndex(int)
     */
    public MenuBarItemBuilder tabIndex(int v0) {
        menuBarItem.setTabIndex(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setText(java.lang.String)
     */
    public MenuBarItemBuilder text(java.lang.String v0) {
        menuBarItem.setText(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setTitle(java.lang.String)
     */
    public MenuBarItemBuilder title(java.lang.String v0) {
        menuBarItem.setTitle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setToolTip(java.lang.String)
     */
    public MenuBarItemBuilder toolTip(java.lang.String v0) {
        menuBarItem.setToolTip(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setToolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig)
     */
    public MenuBarItemBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        menuBarItem.setToolTipConfig(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setVisible(boolean)
     */
    public MenuBarItemBuilder visible(boolean v0) {
        menuBarItem.setVisible(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setWidth(int)
     */
    public MenuBarItemBuilder width(int v0) {
        menuBarItem.setWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBarItem#setWidth(java.lang.String)
     */
    public MenuBarItemBuilder width(java.lang.String v0) {
        menuBarItem.setWidth(v0);
        return this;
    }
}
