package biz.freshcode.learn.gwtp.client.builder.gxt.menu;

import com.sencha.gxt.widget.core.client.menu.MenuBar;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.widget.core.client.menu.MenuBar
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwtp.client.builder.BeanBuilder(MenuBar.class)
public class MenuBarBuilder extends biz.freshcode.learn.gwtp.client.builder.Construct.Parent<MenuBarBuilder> {
    public final MenuBar menuBar;

    public MenuBarBuilder(MenuBar v) {
        menuBar = v;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#MenuBar(com.sencha.gxt.widget.core.client.menu.MenuBar.MenuBarAppearance)
     */
    public MenuBarBuilder(com.sencha.gxt.widget.core.client.menu.MenuBar.MenuBarAppearance v0) {
        this(new MenuBar(v0));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#MenuBar()
     */
    public MenuBarBuilder() {
        this(new MenuBar());
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#add(com.google.gwt.user.client.ui.Widget)
     */
    public MenuBarBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        menuBar.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public MenuBarBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        menuBar.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#addStyleDependentName(java.lang.String)
     */
    public MenuBarBuilder addStyleDependentName(java.lang.String v0) {
        menuBar.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#addStyleName(java.lang.String)
     */
    public MenuBarBuilder addStyleName(java.lang.String v0) {
        menuBar.addStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#addStyleOnOver(com.google.gwt.dom.client.Element, java.lang.String)
     */
    public MenuBarBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        menuBar.addStyleOnOver(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setActiveItem(com.sencha.gxt.widget.core.client.menu.MenuBarItem, boolean)
     */
    public MenuBarBuilder activeItem(com.sencha.gxt.widget.core.client.menu.MenuBarItem v0, boolean v1) {
        menuBar.setActiveItem(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setActiveItem(com.sencha.gxt.widget.core.client.menu.MenuBarItem, boolean, boolean)
     */
    public MenuBarBuilder activeItem(com.sencha.gxt.widget.core.client.menu.MenuBarItem v0, boolean v1, boolean v2) {
        menuBar.setActiveItem(v0, v1, v2);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setAllowTextSelection(boolean)
     */
    public MenuBarBuilder allowTextSelection(boolean v0) {
        menuBar.setAllowTextSelection(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setBorders(boolean)
     */
    public MenuBarBuilder borders(boolean v0) {
        menuBar.setBorders(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setBounds(com.sencha.gxt.core.client.util.Rectangle)
     */
    public MenuBarBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        menuBar.setBounds(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setBounds(int, int, int, int)
     */
    public MenuBarBuilder bounds(int v0, int v1, int v2, int v3) {
        menuBar.setBounds(v0, v1, v2, v3);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setContextMenu(com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public MenuBarBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        menuBar.setContextMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setData(java.lang.String, java.lang.Object)
     */
    public MenuBarBuilder data(java.lang.String v0, java.lang.Object v1) {
        menuBar.setData(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setDeferHeight(boolean)
     */
    public MenuBarBuilder deferHeight(boolean v0) {
        menuBar.setDeferHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setEnabled(boolean)
     */
    public MenuBarBuilder enabled(boolean v0) {
        menuBar.setEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setHeight(java.lang.String)
     */
    public MenuBarBuilder height(java.lang.String v0) {
        menuBar.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setHeight(int)
     */
    public MenuBarBuilder height(int v0) {
        menuBar.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setHideMode(com.sencha.gxt.core.client.Style.HideMode)
     */
    public MenuBarBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        menuBar.setHideMode(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setId(java.lang.String)
     */
    public MenuBarBuilder id(java.lang.String v0) {
        menuBar.setId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setItemId(java.lang.String)
     */
    public MenuBarBuilder itemId(java.lang.String v0) {
        menuBar.setItemId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setLayoutData(java.lang.Object)
     */
    public MenuBarBuilder layoutData(java.lang.Object v0) {
        menuBar.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setPagePosition(int, int)
     */
    public MenuBarBuilder pagePosition(int v0, int v1) {
        menuBar.setPagePosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setPixelSize(int, int)
     */
    public MenuBarBuilder pixelSize(int v0, int v1) {
        menuBar.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setPosition(int, int)
     */
    public MenuBarBuilder position(int v0, int v1) {
        menuBar.setPosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setShadow(boolean)
     */
    public MenuBarBuilder shadow(boolean v0) {
        menuBar.setShadow(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setShadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition)
     */
    public MenuBarBuilder shadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition v0) {
        menuBar.setShadowPosition(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setSize(java.lang.String, java.lang.String)
     */
    public MenuBarBuilder size(java.lang.String v0, java.lang.String v1) {
        menuBar.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setStateId(java.lang.String)
     */
    public MenuBarBuilder stateId(java.lang.String v0) {
        menuBar.setStateId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setStateful(boolean)
     */
    public MenuBarBuilder stateful(boolean v0) {
        menuBar.setStateful(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setStyleDependentName(java.lang.String, boolean)
     */
    public MenuBarBuilder styleDependentName(java.lang.String v0, boolean v1) {
        menuBar.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setStyleName(java.lang.String)
     */
    public MenuBarBuilder styleName(java.lang.String v0) {
        menuBar.setStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setStyleName(java.lang.String, boolean)
     */
    public MenuBarBuilder styleName(java.lang.String v0, boolean v1) {
        menuBar.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setStylePrimaryName(java.lang.String)
     */
    public MenuBarBuilder stylePrimaryName(java.lang.String v0) {
        menuBar.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setTabIndex(int)
     */
    public MenuBarBuilder tabIndex(int v0) {
        menuBar.setTabIndex(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setTitle(java.lang.String)
     */
    public MenuBarBuilder title(java.lang.String v0) {
        menuBar.setTitle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setToolTip(java.lang.String)
     */
    public MenuBarBuilder toolTip(java.lang.String v0) {
        menuBar.setToolTip(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setToolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig)
     */
    public MenuBarBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        menuBar.setToolTipConfig(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setVisible(boolean)
     */
    public MenuBarBuilder visible(boolean v0) {
        menuBar.setVisible(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setWidth(java.lang.String)
     */
    public MenuBarBuilder width(java.lang.String v0) {
        menuBar.setWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.menu.MenuBar#setWidth(int)
     */
    public MenuBarBuilder width(int v0) {
        menuBar.setWidth(v0);
        return this;
    }
}
