package biz.freshcode.learn.gwt.client.builder.gxt.container;

import com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt.client.builder.BeanBuilder(HorizontalLayoutContainer.class)
public class HorizontalLayoutContainerBuilder extends biz.freshcode.learn.gwt.client.builder.Construct.Parent<HorizontalLayoutContainerBuilder> {
    public final HorizontalLayoutContainer horizontalLayoutContainer;

    public HorizontalLayoutContainerBuilder(HorizontalLayoutContainer v) {
        horizontalLayoutContainer = v;
    }

    public HorizontalLayoutContainerBuilder() {
        this(new HorizontalLayoutContainer());
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public HorizontalLayoutContainerBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        horizontalLayoutContainer.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#add(com.google.gwt.user.client.ui.Widget)
     */
    public HorizontalLayoutContainerBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        horizontalLayoutContainer.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#add(com.google.gwt.user.client.ui.IsWidget, com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer.HorizontalLayoutData)
     */
    public HorizontalLayoutContainerBuilder add(com.google.gwt.user.client.ui.IsWidget v0, com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer.HorizontalLayoutData v1) {
        horizontalLayoutContainer.add(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#addStyleDependentName(java.lang.String)
     */
    public HorizontalLayoutContainerBuilder addStyleDependentName(java.lang.String v0) {
        horizontalLayoutContainer.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#addStyleName(java.lang.String)
     */
    public HorizontalLayoutContainerBuilder addStyleName(java.lang.String v0) {
        horizontalLayoutContainer.addStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#addStyleOnOver(com.google.gwt.dom.client.Element, java.lang.String)
     */
    public HorizontalLayoutContainerBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        horizontalLayoutContainer.addStyleOnOver(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setAdjustForScroll(boolean)
     */
    public HorizontalLayoutContainerBuilder adjustForScroll(boolean v0) {
        horizontalLayoutContainer.setAdjustForScroll(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setAllowTextSelection(boolean)
     */
    public HorizontalLayoutContainerBuilder allowTextSelection(boolean v0) {
        horizontalLayoutContainer.setAllowTextSelection(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setBorders(boolean)
     */
    public HorizontalLayoutContainerBuilder borders(boolean v0) {
        horizontalLayoutContainer.setBorders(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setBounds(com.sencha.gxt.core.client.util.Rectangle)
     */
    public HorizontalLayoutContainerBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        horizontalLayoutContainer.setBounds(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setBounds(int, int, int, int)
     */
    public HorizontalLayoutContainerBuilder bounds(int v0, int v1, int v2, int v3) {
        horizontalLayoutContainer.setBounds(v0, v1, v2, v3);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setContextMenu(com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public HorizontalLayoutContainerBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        horizontalLayoutContainer.setContextMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setData(java.lang.String, java.lang.Object)
     */
    public HorizontalLayoutContainerBuilder data(java.lang.String v0, java.lang.Object v1) {
        horizontalLayoutContainer.setData(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setDeferHeight(boolean)
     */
    public HorizontalLayoutContainerBuilder deferHeight(boolean v0) {
        horizontalLayoutContainer.setDeferHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setEnabled(boolean)
     */
    public HorizontalLayoutContainerBuilder enabled(boolean v0) {
        horizontalLayoutContainer.setEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setHeight(int)
     */
    public HorizontalLayoutContainerBuilder height(int v0) {
        horizontalLayoutContainer.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setHeight(java.lang.String)
     */
    public HorizontalLayoutContainerBuilder height(java.lang.String v0) {
        horizontalLayoutContainer.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setHideMode(com.sencha.gxt.core.client.Style.HideMode)
     */
    public HorizontalLayoutContainerBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        horizontalLayoutContainer.setHideMode(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setId(java.lang.String)
     */
    public HorizontalLayoutContainerBuilder id(java.lang.String v0) {
        horizontalLayoutContainer.setId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setItemId(java.lang.String)
     */
    public HorizontalLayoutContainerBuilder itemId(java.lang.String v0) {
        horizontalLayoutContainer.setItemId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setLayoutData(java.lang.Object)
     */
    public HorizontalLayoutContainerBuilder layoutData(java.lang.Object v0) {
        horizontalLayoutContainer.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setPagePosition(int, int)
     */
    public HorizontalLayoutContainerBuilder pagePosition(int v0, int v1) {
        horizontalLayoutContainer.setPagePosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setPixelSize(int, int)
     */
    public HorizontalLayoutContainerBuilder pixelSize(int v0, int v1) {
        horizontalLayoutContainer.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setPosition(int, int)
     */
    public HorizontalLayoutContainerBuilder position(int v0, int v1) {
        horizontalLayoutContainer.setPosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setScrollMode(com.sencha.gxt.core.client.dom.ScrollSupport.ScrollMode)
     */
    public HorizontalLayoutContainerBuilder scrollMode(com.sencha.gxt.core.client.dom.ScrollSupport.ScrollMode v0) {
        horizontalLayoutContainer.setScrollMode(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setScrollSupport(com.sencha.gxt.core.client.dom.ScrollSupport)
     */
    public HorizontalLayoutContainerBuilder scrollSupport(com.sencha.gxt.core.client.dom.ScrollSupport v0) {
        horizontalLayoutContainer.setScrollSupport(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setShadow(boolean)
     */
    public HorizontalLayoutContainerBuilder shadow(boolean v0) {
        horizontalLayoutContainer.setShadow(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setShadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition)
     */
    public HorizontalLayoutContainerBuilder shadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition v0) {
        horizontalLayoutContainer.setShadowPosition(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setSize(java.lang.String, java.lang.String)
     */
    public HorizontalLayoutContainerBuilder size(java.lang.String v0, java.lang.String v1) {
        horizontalLayoutContainer.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setStateId(java.lang.String)
     */
    public HorizontalLayoutContainerBuilder stateId(java.lang.String v0) {
        horizontalLayoutContainer.setStateId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setStateful(boolean)
     */
    public HorizontalLayoutContainerBuilder stateful(boolean v0) {
        horizontalLayoutContainer.setStateful(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setStyleDependentName(java.lang.String, boolean)
     */
    public HorizontalLayoutContainerBuilder styleDependentName(java.lang.String v0, boolean v1) {
        horizontalLayoutContainer.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setStyleName(java.lang.String)
     */
    public HorizontalLayoutContainerBuilder styleName(java.lang.String v0) {
        horizontalLayoutContainer.setStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setStyleName(java.lang.String, boolean)
     */
    public HorizontalLayoutContainerBuilder styleName(java.lang.String v0, boolean v1) {
        horizontalLayoutContainer.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setStylePrimaryName(java.lang.String)
     */
    public HorizontalLayoutContainerBuilder stylePrimaryName(java.lang.String v0) {
        horizontalLayoutContainer.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setTabIndex(int)
     */
    public HorizontalLayoutContainerBuilder tabIndex(int v0) {
        horizontalLayoutContainer.setTabIndex(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setTitle(java.lang.String)
     */
    public HorizontalLayoutContainerBuilder title(java.lang.String v0) {
        horizontalLayoutContainer.setTitle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setToolTip(java.lang.String)
     */
    public HorizontalLayoutContainerBuilder toolTip(java.lang.String v0) {
        horizontalLayoutContainer.setToolTip(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setToolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig)
     */
    public HorizontalLayoutContainerBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        horizontalLayoutContainer.setToolTipConfig(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setVisible(boolean)
     */
    public HorizontalLayoutContainerBuilder visible(boolean v0) {
        horizontalLayoutContainer.setVisible(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setWidth(int)
     */
    public HorizontalLayoutContainerBuilder width(int v0) {
        horizontalLayoutContainer.setWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HorizontalLayoutContainer#setWidth(java.lang.String)
     */
    public HorizontalLayoutContainerBuilder width(java.lang.String v0) {
        horizontalLayoutContainer.setWidth(v0);
        return this;
    }
}
