package biz.freshcode.learn.gwt_bootstrap.client.builder.com.google.gwt.user.client.ui;

import com.google.gwt.user.client.ui.SimplePanel;

/**
 * Generated by BuilderGenerator
 *
 * @see com.google.gwt.user.client.ui.SimplePanel
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt_bootstrap.client.builder.BeanBuilder(SimplePanel.class)
public class SimplePanelBuilder extends biz.freshcode.learn.gwt_bootstrap.client.builder.Construct.Parent<SimplePanelBuilder> {
    public final SimplePanel simplePanel;

    public SimplePanelBuilder(SimplePanel v) {
        simplePanel = v;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#SimplePanel()
     */
    public SimplePanelBuilder() {
        this(new SimplePanel());
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#SimplePanel(com.google.gwt.user.client.ui.Widget)
     */
    public SimplePanelBuilder(com.google.gwt.user.client.ui.Widget v0) {
        this(new SimplePanel(v0));
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#add(com.google.gwt.user.client.ui.Widget)
     */
    public SimplePanelBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        simplePanel.add(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public SimplePanelBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        simplePanel.add(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#addStyleDependentName(java.lang.String)
     */
    public SimplePanelBuilder addStyleDependentName(java.lang.String v0) {
        simplePanel.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#addStyleName(java.lang.String)
     */
    public SimplePanelBuilder addStyleName(java.lang.String v0) {
        simplePanel.addStyleName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setHeight(java.lang.String)
     */
    public SimplePanelBuilder height(java.lang.String v0) {
        simplePanel.setHeight(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setLayoutData(java.lang.Object)
     */
    public SimplePanelBuilder layoutData(java.lang.Object v0) {
        simplePanel.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setPixelSize(int, int)
     */
    public SimplePanelBuilder pixelSize(int v0, int v1) {
        simplePanel.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setSize(java.lang.String, java.lang.String)
     */
    public SimplePanelBuilder size(java.lang.String v0, java.lang.String v1) {
        simplePanel.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setStyleDependentName(java.lang.String, boolean)
     */
    public SimplePanelBuilder styleDependentName(java.lang.String v0, boolean v1) {
        simplePanel.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setStyleName(java.lang.String)
     */
    public SimplePanelBuilder styleName(java.lang.String v0) {
        simplePanel.setStyleName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setStyleName(java.lang.String, boolean)
     */
    public SimplePanelBuilder styleName(java.lang.String v0, boolean v1) {
        simplePanel.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setStylePrimaryName(java.lang.String)
     */
    public SimplePanelBuilder stylePrimaryName(java.lang.String v0) {
        simplePanel.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setTitle(java.lang.String)
     */
    public SimplePanelBuilder title(java.lang.String v0) {
        simplePanel.setTitle(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setVisible(boolean)
     */
    public SimplePanelBuilder visible(boolean v0) {
        simplePanel.setVisible(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setWidget(com.google.gwt.user.client.ui.Widget)
     */
    public SimplePanelBuilder widget(com.google.gwt.user.client.ui.Widget v0) {
        simplePanel.setWidget(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setWidget(com.google.gwt.user.client.ui.IsWidget)
     */
    public SimplePanelBuilder widget(com.google.gwt.user.client.ui.IsWidget v0) {
        simplePanel.setWidget(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.SimplePanel#setWidth(java.lang.String)
     */
    public SimplePanelBuilder width(java.lang.String v0) {
        simplePanel.setWidth(v0);
        return this;
    }
}
