package biz.freshcode.learn.gwt.client.uispike.builder;

import com.sencha.gxt.widget.core.client.container.BorderLayoutContainer.BorderLayoutData;

// Generated by BeanBuilderGenerator
@BeanBuilder(BorderLayoutData.class)
public class BorderLayoutDataBuilder {
    public final BorderLayoutData borderLayoutData;

    public BorderLayoutDataBuilder() {
        this(new BorderLayoutData());
    }

    public BorderLayoutDataBuilder(BorderLayoutData v) {
        borderLayoutData = v;
    }

    public BorderLayoutDataBuilder size(double v) {
        borderLayoutData.setSize(v);
        return this;
    }

    public BorderLayoutDataBuilder collapsed(boolean v) {
        borderLayoutData.setCollapsed(v);
        return this;
    }

    public BorderLayoutDataBuilder collapseHidden(boolean v) {
        borderLayoutData.setCollapseHidden(v);
        return this;
    }

    public BorderLayoutDataBuilder collapseMini(boolean v) {
        borderLayoutData.setCollapseMini(v);
        return this;
    }

    public BorderLayoutDataBuilder collapsible(boolean v) {
        borderLayoutData.setCollapsible(v);
        return this;
    }

    public BorderLayoutDataBuilder floatable(boolean v) {
        borderLayoutData.setFloatable(v);
        return this;
    }

    public BorderLayoutDataBuilder hidden(boolean v) {
        borderLayoutData.setHidden(v);
        return this;
    }

    public BorderLayoutDataBuilder maxSize(int v) {
        borderLayoutData.setMaxSize(v);
        return this;
    }

    public BorderLayoutDataBuilder minSize(int v) {
        borderLayoutData.setMinSize(v);
        return this;
    }

    public BorderLayoutDataBuilder split(boolean v) {
        borderLayoutData.setSplit(v);
        return this;
    }

    public BorderLayoutDataBuilder margins(com.sencha.gxt.core.client.util.Margins v) {
        borderLayoutData.setMargins(v);
        return this;
    }
}
