package biz.freshcode.learn.gwt.client.uispike.builder;

import com.sencha.gxt.widget.core.client.Dialog;

// Generated by BeanBuilderGenerator
@BeanBuilder(Dialog.class)
public class DialogBuilder {
    public final Dialog dialog;

    public DialogBuilder() {
        this(new Dialog());
    }

    public DialogBuilder(Dialog v) {
        dialog = v;
    }

    public DialogBuilder dialogMessages(com.sencha.gxt.widget.core.client.Dialog.DialogMessages v0) {
        dialog.setDialogMessages(v0);
        return this;
    }

    public DialogBuilder hideOnButtonClick(boolean v0) {
        dialog.setHideOnButtonClick(v0);
        return this;
    }

    public DialogBuilder predefinedButtons(com.sencha.gxt.widget.core.client.Dialog.PredefinedButton... v0) {
        dialog.setPredefinedButtons(v0);
        return this;
    }

    public DialogBuilder focusWidget(com.google.gwt.user.client.ui.Widget v0) {
        dialog.setFocusWidget(v0);
        return this;
    }

    public DialogBuilder active(boolean v0) {
        dialog.setActive(v0);
        return this;
    }

    public DialogBuilder autoHide(boolean v0) {
        dialog.setAutoHide(v0);
        return this;
    }

    public DialogBuilder blinkModal(boolean v0) {
        dialog.setBlinkModal(v0);
        return this;
    }

    public DialogBuilder closable(boolean v0) {
        dialog.setClosable(v0);
        return this;
    }

    public DialogBuilder constrain(boolean v0) {
        dialog.setConstrain(v0);
        return this;
    }

    public DialogBuilder container(com.google.gwt.user.client.Element v0) {
        dialog.setContainer(v0);
        return this;
    }

    public DialogBuilder draggable(boolean v0) {
        dialog.setDraggable(v0);
        return this;
    }

    public DialogBuilder maximizable(boolean v0) {
        dialog.setMaximizable(v0);
        return this;
    }

    public DialogBuilder minHeight(int v0) {
        dialog.setMinHeight(v0);
        return this;
    }

    public DialogBuilder minimizable(boolean v0) {
        dialog.setMinimizable(v0);
        return this;
    }

    public DialogBuilder minWidth(int v0) {
        dialog.setMinWidth(v0);
        return this;
    }

    public DialogBuilder modal(boolean v0) {
        dialog.setModal(v0);
        return this;
    }

    public DialogBuilder onEsc(boolean v0) {
        dialog.setOnEsc(v0);
        return this;
    }

    public DialogBuilder pagePosition(int v0, int v1) {
        dialog.setPagePosition(v0, v1);
        return this;
    }

    public DialogBuilder position(int v0, int v1) {
        dialog.setPosition(v0, v1);
        return this;
    }

    public DialogBuilder resizable(boolean v0) {
        dialog.setResizable(v0);
        return this;
    }

    public DialogBuilder windowMessages(com.sencha.gxt.widget.core.client.Window.WindowMessages v0) {
        dialog.setWindowMessages(v0);
        return this;
    }

    public DialogBuilder zIndex(int v0) {
        dialog.setZIndex(v0);
        return this;
    }

    public DialogBuilder addButton(com.google.gwt.user.client.ui.Widget v0) {
        dialog.addButton(v0);
        return this;
    }

    public DialogBuilder addTool(com.google.gwt.user.client.ui.Widget v0) {
        dialog.addTool(v0);
        return this;
    }

    public DialogBuilder animationDuration(int v0) {
        dialog.setAnimationDuration(v0);
        return this;
    }

    public DialogBuilder animCollapse(boolean v0) {
        dialog.setAnimCollapse(v0);
        return this;
    }

    public DialogBuilder bodyBorder(boolean v0) {
        dialog.setBodyBorder(v0);
        return this;
    }

    public DialogBuilder bodyStyle(java.lang.String v0) {
        dialog.setBodyStyle(v0);
        return this;
    }

    public DialogBuilder bodyStyleName(java.lang.String v0) {
        dialog.setBodyStyleName(v0);
        return this;
    }

    public DialogBuilder buttonAlign(com.sencha.gxt.widget.core.client.container.BoxLayoutContainer.BoxLayoutPack v0) {
        dialog.setButtonAlign(v0);
        return this;
    }

    public DialogBuilder collapsible(boolean v0) {
        dialog.setCollapsible(v0);
        return this;
    }

    public DialogBuilder expanded(boolean v0) {
        dialog.setExpanded(v0);
        return this;
    }

    public DialogBuilder headerVisible(boolean v0) {
        dialog.setHeaderVisible(v0);
        return this;
    }

    public DialogBuilder headingHtml(com.google.gwt.safehtml.shared.SafeHtml v0) {
        dialog.setHeadingHtml(v0);
        return this;
    }

    public DialogBuilder headingHtml(java.lang.String v0) {
        dialog.setHeadingHtml(v0);
        return this;
    }

    public DialogBuilder headingText(java.lang.String v0) {
        dialog.setHeadingText(v0);
        return this;
    }

    public DialogBuilder hideCollapseTool(boolean v0) {
        dialog.setHideCollapseTool(v0);
        return this;
    }

    public DialogBuilder messages(com.sencha.gxt.widget.core.client.ContentPanel.ContentPanelMessages v0) {
        dialog.setMessages(v0);
        return this;
    }

    public DialogBuilder minButtonWidth(int v0) {
        dialog.setMinButtonWidth(v0);
        return this;
    }

    public DialogBuilder titleCollapse(boolean v0) {
        dialog.setTitleCollapse(v0);
        return this;
    }

    public DialogBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        dialog.add(v0);
        return this;
    }

    public DialogBuilder add(com.google.gwt.user.client.ui.Widget v0, com.sencha.gxt.widget.core.client.container.MarginData v1) {
        dialog.add(v0, v1);
        return this;
    }

    public DialogBuilder resize(boolean v0) {
        dialog.setResize(v0);
        return this;
    }

    public DialogBuilder widget(com.google.gwt.user.client.ui.IsWidget v0) {
        dialog.setWidget(v0);
        return this;
    }

    public DialogBuilder widget(com.google.gwt.user.client.ui.Widget v0) {
        dialog.setWidget(v0);
        return this;
    }

    public DialogBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        dialog.add(v0);
        return this;
    }

    public DialogBuilder size(java.lang.String v0, java.lang.String v1) {
        dialog.setSize(v0, v1);
        return this;
    }

    public DialogBuilder itemId(java.lang.String v0) {
        dialog.setItemId(v0);
        return this;
    }

    public DialogBuilder shadow(boolean v0) {
        dialog.setShadow(v0);
        return this;
    }

    public DialogBuilder tabIndex(int v0) {
        dialog.setTabIndex(v0);
        return this;
    }

    public DialogBuilder visible(boolean v0) {
        dialog.setVisible(v0);
        return this;
    }

    public DialogBuilder enabled(boolean v0) {
        dialog.setEnabled(v0);
        return this;
    }

    public DialogBuilder pixelSize(int v0, int v1) {
        dialog.setPixelSize(v0, v1);
        return this;
    }

    public DialogBuilder width(int v0) {
        dialog.setWidth(v0);
        return this;
    }

    public DialogBuilder width(java.lang.String v0) {
        dialog.setWidth(v0);
        return this;
    }

    public DialogBuilder height(int v0) {
        dialog.setHeight(v0);
        return this;
    }

    public DialogBuilder height(java.lang.String v0) {
        dialog.setHeight(v0);
        return this;
    }

    public DialogBuilder bounds(int v0, int v1, int v2, int v3) {
        dialog.setBounds(v0, v1, v2, v3);
        return this;
    }

    public DialogBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        dialog.setBounds(v0);
        return this;
    }

    public DialogBuilder deferHeight(boolean v0) {
        dialog.setDeferHeight(v0);
        return this;
    }

    public DialogBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        dialog.addStyleOnOver(v0, v1);
        return this;
    }

    public DialogBuilder allowTextSelection(boolean v0) {
        dialog.setAllowTextSelection(v0);
        return this;
    }

    public DialogBuilder borders(boolean v0) {
        dialog.setBorders(v0);
        return this;
    }

    public DialogBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        dialog.setContextMenu(v0);
        return this;
    }

    public DialogBuilder data(java.lang.String v0, java.lang.Object v1) {
        dialog.setData(v0, v1);
        return this;
    }

    public DialogBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        dialog.setHideMode(v0);
        return this;
    }

    public DialogBuilder id(java.lang.String v0) {
        dialog.setId(v0);
        return this;
    }

    public DialogBuilder stateful(boolean v0) {
        dialog.setStateful(v0);
        return this;
    }

    public DialogBuilder stateId(java.lang.String v0) {
        dialog.setStateId(v0);
        return this;
    }

    public DialogBuilder toolTip(java.lang.String v0) {
        dialog.setToolTip(v0);
        return this;
    }

    public DialogBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        dialog.setToolTipConfig(v0);
        return this;
    }

    public DialogBuilder layoutData(java.lang.Object v0) {
        dialog.setLayoutData(v0);
        return this;
    }

    public DialogBuilder addStyleDependentName(java.lang.String v0) {
        dialog.addStyleDependentName(v0);
        return this;
    }

    public DialogBuilder addStyleName(java.lang.String v0) {
        dialog.addStyleName(v0);
        return this;
    }

    public DialogBuilder styleDependentName(java.lang.String v0, boolean v1) {
        dialog.setStyleDependentName(v0, v1);
        return this;
    }

    public DialogBuilder styleName(java.lang.String v0, boolean v1) {
        dialog.setStyleName(v0, v1);
        return this;
    }

    public DialogBuilder styleName(java.lang.String v0) {
        dialog.setStyleName(v0);
        return this;
    }

    public DialogBuilder stylePrimaryName(java.lang.String v0) {
        dialog.setStylePrimaryName(v0);
        return this;
    }

    public DialogBuilder title(java.lang.String v0) {
        dialog.setTitle(v0);
        return this;
    }
}
