package biz.freshcode.learn.gwt.client.uispike.builder;

import com.sencha.gxt.widget.core.client.FramedPanel;

// Generated by BeanBuilderGenerator
@BeanBuilder(FramedPanel.class)
public class FramedPanelBuilder {
  public final FramedPanel framedPanel;

  public FramedPanelBuilder() {
    this(new FramedPanel());
  }

  public FramedPanelBuilder(FramedPanel v) {
    framedPanel = v;
  }

  public FramedPanelBuilder addButton(com.google.gwt.user.client.ui.Widget v0) {
    framedPanel.addButton(v0);
    return this;
  }

  public FramedPanelBuilder addTool(com.google.gwt.user.client.ui.Widget v0) {
    framedPanel.addTool(v0);
    return this;
  }

  public FramedPanelBuilder animationDuration(int v0) {
    framedPanel.setAnimationDuration(v0);
    return this;
  }

  public FramedPanelBuilder animCollapse(boolean v0) {
    framedPanel.setAnimCollapse(v0);
    return this;
  }

  public FramedPanelBuilder bodyBorder(boolean v0) {
    framedPanel.setBodyBorder(v0);
    return this;
  }

  public FramedPanelBuilder bodyStyle(java.lang.String v0) {
    framedPanel.setBodyStyle(v0);
    return this;
  }

  public FramedPanelBuilder bodyStyleName(java.lang.String v0) {
    framedPanel.setBodyStyleName(v0);
    return this;
  }

  public FramedPanelBuilder buttonAlign(com.sencha.gxt.widget.core.client.container.BoxLayoutContainer.BoxLayoutPack v0) {
    framedPanel.setButtonAlign(v0);
    return this;
  }

  public FramedPanelBuilder collapsible(boolean v0) {
    framedPanel.setCollapsible(v0);
    return this;
  }

  public FramedPanelBuilder expanded(boolean v0) {
    framedPanel.setExpanded(v0);
    return this;
  }

  public FramedPanelBuilder headerVisible(boolean v0) {
    framedPanel.setHeaderVisible(v0);
    return this;
  }

  public FramedPanelBuilder headingHtml(com.google.gwt.safehtml.shared.SafeHtml v0) {
    framedPanel.setHeadingHtml(v0);
    return this;
  }

  public FramedPanelBuilder headingHtml(java.lang.String v0) {
    framedPanel.setHeadingHtml(v0);
    return this;
  }

  public FramedPanelBuilder headingText(java.lang.String v0) {
    framedPanel.setHeadingText(v0);
    return this;
  }

  public FramedPanelBuilder hideCollapseTool(boolean v0) {
    framedPanel.setHideCollapseTool(v0);
    return this;
  }

  public FramedPanelBuilder messages(com.sencha.gxt.widget.core.client.ContentPanel.ContentPanelMessages v0) {
    framedPanel.setMessages(v0);
    return this;
  }

  public FramedPanelBuilder minButtonWidth(int v0) {
    framedPanel.setMinButtonWidth(v0);
    return this;
  }

  public FramedPanelBuilder titleCollapse(boolean v0) {
    framedPanel.setTitleCollapse(v0);
    return this;
  }

  public FramedPanelBuilder add(com.google.gwt.user.client.ui.Widget v0) {
    framedPanel.add(v0);
    return this;
  }

  public FramedPanelBuilder add(com.google.gwt.user.client.ui.Widget v0, com.sencha.gxt.widget.core.client.container.MarginData v1) {
    framedPanel.add(v0, v1);
    return this;
  }

  public FramedPanelBuilder resize(boolean v0) {
    framedPanel.setResize(v0);
    return this;
  }

  public FramedPanelBuilder widget(com.google.gwt.user.client.ui.IsWidget v0) {
    framedPanel.setWidget(v0);
    return this;
  }

  public FramedPanelBuilder widget(com.google.gwt.user.client.ui.Widget v0) {
    framedPanel.setWidget(v0);
    return this;
  }

  public FramedPanelBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
    framedPanel.add(v0);
    return this;
  }

  public FramedPanelBuilder size(java.lang.String v0, java.lang.String v1) {
    framedPanel.setSize(v0, v1);
    return this;
  }

  public FramedPanelBuilder deferHeight(boolean v0) {
    framedPanel.setDeferHeight(v0);
    return this;
  }

  public FramedPanelBuilder visible(boolean v0) {
    framedPanel.setVisible(v0);
    return this;
  }

  public FramedPanelBuilder width(int v0) {
    framedPanel.setWidth(v0);
    return this;
  }

  public FramedPanelBuilder width(java.lang.String v0) {
    framedPanel.setWidth(v0);
    return this;
  }

  public FramedPanelBuilder height(int v0) {
    framedPanel.setHeight(v0);
    return this;
  }

  public FramedPanelBuilder height(java.lang.String v0) {
    framedPanel.setHeight(v0);
    return this;
  }

  public FramedPanelBuilder pixelSize(int v0, int v1) {
    framedPanel.setPixelSize(v0, v1);
    return this;
  }

  public FramedPanelBuilder position(int v0, int v1) {
    framedPanel.setPosition(v0, v1);
    return this;
  }

  public FramedPanelBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
    framedPanel.addStyleOnOver(v0, v1);
    return this;
  }

  public FramedPanelBuilder allowTextSelection(boolean v0) {
    framedPanel.setAllowTextSelection(v0);
    return this;
  }

  public FramedPanelBuilder borders(boolean v0) {
    framedPanel.setBorders(v0);
    return this;
  }

  public FramedPanelBuilder bounds(int v0, int v1, int v2, int v3) {
    framedPanel.setBounds(v0, v1, v2, v3);
    return this;
  }

  public FramedPanelBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
    framedPanel.setBounds(v0);
    return this;
  }

  public FramedPanelBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
    framedPanel.setContextMenu(v0);
    return this;
  }

  public FramedPanelBuilder data(java.lang.String v0, java.lang.Object v1) {
    framedPanel.setData(v0, v1);
    return this;
  }

  public FramedPanelBuilder enabled(boolean v0) {
    framedPanel.setEnabled(v0);
    return this;
  }

  public FramedPanelBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
    framedPanel.setHideMode(v0);
    return this;
  }

  public FramedPanelBuilder id(java.lang.String v0) {
    framedPanel.setId(v0);
    return this;
  }

  public FramedPanelBuilder itemId(java.lang.String v0) {
    framedPanel.setItemId(v0);
    return this;
  }

  public FramedPanelBuilder pagePosition(int v0, int v1) {
    framedPanel.setPagePosition(v0, v1);
    return this;
  }

  public FramedPanelBuilder shadow(boolean v0) {
    framedPanel.setShadow(v0);
    return this;
  }

  public FramedPanelBuilder stateful(boolean v0) {
    framedPanel.setStateful(v0);
    return this;
  }

  public FramedPanelBuilder stateId(java.lang.String v0) {
    framedPanel.setStateId(v0);
    return this;
  }

  public FramedPanelBuilder tabIndex(int v0) {
    framedPanel.setTabIndex(v0);
    return this;
  }

  public FramedPanelBuilder toolTip(java.lang.String v0) {
    framedPanel.setToolTip(v0);
    return this;
  }

  public FramedPanelBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
    framedPanel.setToolTipConfig(v0);
    return this;
  }

  public FramedPanelBuilder layoutData(java.lang.Object v0) {
    framedPanel.setLayoutData(v0);
    return this;
  }

  public FramedPanelBuilder addStyleDependentName(java.lang.String v0) {
    framedPanel.addStyleDependentName(v0);
    return this;
  }

  public FramedPanelBuilder styleDependentName(java.lang.String v0, boolean v1) {
    framedPanel.setStyleDependentName(v0, v1);
    return this;
  }

  public FramedPanelBuilder addStyleName(java.lang.String v0) {
    framedPanel.addStyleName(v0);
    return this;
  }

  public FramedPanelBuilder styleName(java.lang.String v0, boolean v1) {
    framedPanel.setStyleName(v0, v1);
    return this;
  }

  public FramedPanelBuilder styleName(java.lang.String v0) {
    framedPanel.setStyleName(v0);
    return this;
  }

  public FramedPanelBuilder stylePrimaryName(java.lang.String v0) {
    framedPanel.setStylePrimaryName(v0);
    return this;
  }

  public FramedPanelBuilder title(java.lang.String v0) {
    framedPanel.setTitle(v0);
    return this;
  }
}
