package biz.freshcode.learn.gwt.client.uispike.builder;

import com.sencha.gxt.widget.core.client.container.VerticalLayoutContainer;

// Generated by BeanBuilderGenerator
@BeanBuilder(VerticalLayoutContainer.class)
public class VerticalLayoutContainerBuilder {
    public final VerticalLayoutContainer verticalLayoutContainer;

    public VerticalLayoutContainerBuilder() {
        this(new VerticalLayoutContainer());
    }

    public VerticalLayoutContainerBuilder(VerticalLayoutContainer v) {
        verticalLayoutContainer = v;
    }

    public VerticalLayoutContainerBuilder add(com.google.gwt.user.client.ui.IsWidget v0, com.sencha.gxt.widget.core.client.container.VerticalLayoutContainer.VerticalLayoutData v1) {
        verticalLayoutContainer.add(v0, v1);
        return this;
    }

    public VerticalLayoutContainerBuilder adjustForScroll(boolean v0) {
        verticalLayoutContainer.setAdjustForScroll(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder scrollMode(com.sencha.gxt.core.client.dom.ScrollSupport.ScrollMode v0) {
        verticalLayoutContainer.setScrollMode(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder scrollSupport(com.sencha.gxt.core.client.dom.ScrollSupport v0) {
        verticalLayoutContainer.setScrollSupport(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        verticalLayoutContainer.add(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        verticalLayoutContainer.add(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder size(java.lang.String v0, java.lang.String v1) {
        verticalLayoutContainer.setSize(v0, v1);
        return this;
    }

    public VerticalLayoutContainerBuilder position(int v0, int v1) {
        verticalLayoutContainer.setPosition(v0, v1);
        return this;
    }

    public VerticalLayoutContainerBuilder pixelSize(int v0, int v1) {
        verticalLayoutContainer.setPixelSize(v0, v1);
        return this;
    }

    public VerticalLayoutContainerBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        verticalLayoutContainer.addStyleOnOver(v0, v1);
        return this;
    }

    public VerticalLayoutContainerBuilder allowTextSelection(boolean v0) {
        verticalLayoutContainer.setAllowTextSelection(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder borders(boolean v0) {
        verticalLayoutContainer.setBorders(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder bounds(int v0, int v1, int v2, int v3) {
        verticalLayoutContainer.setBounds(v0, v1, v2, v3);
        return this;
    }

    public VerticalLayoutContainerBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        verticalLayoutContainer.setBounds(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        verticalLayoutContainer.setContextMenu(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder data(java.lang.String v0, java.lang.Object v1) {
        verticalLayoutContainer.setData(v0, v1);
        return this;
    }

    public VerticalLayoutContainerBuilder deferHeight(boolean v0) {
        verticalLayoutContainer.setDeferHeight(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder enabled(boolean v0) {
        verticalLayoutContainer.setEnabled(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder height(int v0) {
        verticalLayoutContainer.setHeight(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder height(java.lang.String v0) {
        verticalLayoutContainer.setHeight(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        verticalLayoutContainer.setHideMode(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder id(java.lang.String v0) {
        verticalLayoutContainer.setId(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder itemId(java.lang.String v0) {
        verticalLayoutContainer.setItemId(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder pagePosition(int v0, int v1) {
        verticalLayoutContainer.setPagePosition(v0, v1);
        return this;
    }

    public VerticalLayoutContainerBuilder shadow(boolean v0) {
        verticalLayoutContainer.setShadow(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder stateful(boolean v0) {
        verticalLayoutContainer.setStateful(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder stateId(java.lang.String v0) {
        verticalLayoutContainer.setStateId(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder tabIndex(int v0) {
        verticalLayoutContainer.setTabIndex(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder toolTip(java.lang.String v0) {
        verticalLayoutContainer.setToolTip(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        verticalLayoutContainer.setToolTipConfig(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder visible(boolean v0) {
        verticalLayoutContainer.setVisible(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder width(int v0) {
        verticalLayoutContainer.setWidth(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder width(java.lang.String v0) {
        verticalLayoutContainer.setWidth(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder layoutData(java.lang.Object v0) {
        verticalLayoutContainer.setLayoutData(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder addStyleDependentName(java.lang.String v0) {
        verticalLayoutContainer.addStyleDependentName(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder styleDependentName(java.lang.String v0, boolean v1) {
        verticalLayoutContainer.setStyleDependentName(v0, v1);
        return this;
    }

    public VerticalLayoutContainerBuilder addStyleName(java.lang.String v0) {
        verticalLayoutContainer.addStyleName(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder styleName(java.lang.String v0, boolean v1) {
        verticalLayoutContainer.setStyleName(v0, v1);
        return this;
    }

    public VerticalLayoutContainerBuilder styleName(java.lang.String v0) {
        verticalLayoutContainer.setStyleName(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder stylePrimaryName(java.lang.String v0) {
        verticalLayoutContainer.setStylePrimaryName(v0);
        return this;
    }

    public VerticalLayoutContainerBuilder title(java.lang.String v0) {
        verticalLayoutContainer.setTitle(v0);
        return this;
    }
}
