package biz.freshcode.learn.gwt.client.uispike.builder;

import com.sencha.gxt.widget.core.client.container.VerticalLayoutContainer.VerticalLayoutData;

// Generated by BeanBuilderGenerator
@BeanBuilder(VerticalLayoutData.class)
public class VerticalLayoutDataBuilder {
    public final VerticalLayoutData verticalLayoutData;

    public VerticalLayoutDataBuilder() {
        this(new VerticalLayoutData());
    }

    public VerticalLayoutDataBuilder(VerticalLayoutData v) {
        verticalLayoutData = v;
    }

    public VerticalLayoutDataBuilder height(double v) {
        verticalLayoutData.setHeight(v);
        return this;
    }

    public VerticalLayoutDataBuilder width(double v) {
        verticalLayoutData.setWidth(v);
        return this;
    }

    public VerticalLayoutDataBuilder margins(com.sencha.gxt.core.client.util.Margins v) {
        verticalLayoutData.setMargins(v);
        return this;
    }
}
