package biz.freshcode.learn.gwt2.common.client.builder.gxt;

import com.sencha.gxt.widget.core.client.FramedPanel;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.widget.core.client.FramedPanel
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt2.common.client.builder.BeanBuilder(FramedPanel.class)
public class FramedPanelBuilder extends biz.freshcode.learn.gwt2.common.client.builder.Construct.Parent<FramedPanelBuilder> {
    public final FramedPanel framedPanel;

    public FramedPanelBuilder(FramedPanel v) {
        framedPanel = v;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#FramedPanel()
     */
    public FramedPanelBuilder() {
        this(new FramedPanel());
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#FramedPanel(com.sencha.gxt.widget.core.client.FramedPanel.FramedPanelAppearance)
     */
    public FramedPanelBuilder(com.sencha.gxt.widget.core.client.FramedPanel.FramedPanelAppearance v0) {
        this(new FramedPanel(v0));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#add(com.google.gwt.user.client.ui.Widget)
     */
    public FramedPanelBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        framedPanel.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public FramedPanelBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        framedPanel.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#add(com.google.gwt.user.client.ui.Widget, com.sencha.gxt.widget.core.client.container.MarginData)
     */
    public FramedPanelBuilder add(com.google.gwt.user.client.ui.Widget v0, com.sencha.gxt.widget.core.client.container.MarginData v1) {
        framedPanel.add(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#add(com.google.gwt.user.client.ui.IsWidget, com.sencha.gxt.widget.core.client.container.MarginData)
     */
    public FramedPanelBuilder add(com.google.gwt.user.client.ui.IsWidget v0, com.sencha.gxt.widget.core.client.container.MarginData v1) {
        framedPanel.add(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#addButton(com.google.gwt.user.client.ui.Widget)
     */
    public FramedPanelBuilder addButton(com.google.gwt.user.client.ui.Widget v0) {
        framedPanel.addButton(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#addGestureRecognizer(com.sencha.gxt.core.client.gestures.GestureRecognizer)
     */
    public FramedPanelBuilder addGestureRecognizer(com.sencha.gxt.core.client.gestures.GestureRecognizer v0) {
        framedPanel.addGestureRecognizer(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#addStyleDependentName(java.lang.String)
     */
    public FramedPanelBuilder addStyleDependentName(java.lang.String v0) {
        framedPanel.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#addStyleName(java.lang.String)
     */
    public FramedPanelBuilder addStyleName(java.lang.String v0) {
        framedPanel.addStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#addStyleOnOver(com.google.gwt.dom.client.Element, java.lang.String)
     */
    public FramedPanelBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        framedPanel.addStyleOnOver(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#addTool(com.google.gwt.user.client.ui.Widget)
     */
    public FramedPanelBuilder addTool(com.google.gwt.user.client.ui.Widget v0) {
        framedPanel.addTool(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setAdjustSize(boolean)
     */
    public FramedPanelBuilder adjustSize(boolean v0) {
        framedPanel.setAdjustSize(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setAllowTextSelection(boolean)
     */
    public FramedPanelBuilder allowTextSelection(boolean v0) {
        framedPanel.setAllowTextSelection(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setAnimCollapse(boolean)
     */
    public FramedPanelBuilder animCollapse(boolean v0) {
        framedPanel.setAnimCollapse(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setAnimationDuration(int)
     */
    public FramedPanelBuilder animationDuration(int v0) {
        framedPanel.setAnimationDuration(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setBodyBorder(boolean)
     */
    public FramedPanelBuilder bodyBorder(boolean v0) {
        framedPanel.setBodyBorder(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setBodyStyle(java.lang.String)
     */
    public FramedPanelBuilder bodyStyle(java.lang.String v0) {
        framedPanel.setBodyStyle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setBodyStyleName(java.lang.String)
     */
    public FramedPanelBuilder bodyStyleName(java.lang.String v0) {
        framedPanel.setBodyStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setBorders(boolean)
     */
    public FramedPanelBuilder borders(boolean v0) {
        framedPanel.setBorders(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setBounds(com.sencha.gxt.core.client.util.Rectangle)
     */
    public FramedPanelBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        framedPanel.setBounds(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setBounds(int, int, int, int)
     */
    public FramedPanelBuilder bounds(int v0, int v1, int v2, int v3) {
        framedPanel.setBounds(v0, v1, v2, v3);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setButtonAlign(com.sencha.gxt.widget.core.client.container.BoxLayoutContainer.BoxLayoutPack)
     */
    public FramedPanelBuilder buttonAlign(com.sencha.gxt.widget.core.client.container.BoxLayoutContainer.BoxLayoutPack v0) {
        framedPanel.setButtonAlign(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setCollapsible(boolean)
     */
    public FramedPanelBuilder collapsible(boolean v0) {
        framedPanel.setCollapsible(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setContextMenu(com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public FramedPanelBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        framedPanel.setContextMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setData(java.lang.String, java.lang.Object)
     */
    public FramedPanelBuilder data(java.lang.String v0, java.lang.Object v1) {
        framedPanel.setData(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setDeferHeight(boolean)
     */
    public FramedPanelBuilder deferHeight(boolean v0) {
        framedPanel.setDeferHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setEnabled(boolean)
     */
    public FramedPanelBuilder enabled(boolean v0) {
        framedPanel.setEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setExpanded(boolean)
     */
    public FramedPanelBuilder expanded(boolean v0) {
        framedPanel.setExpanded(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setHeaderVisible(boolean)
     */
    public FramedPanelBuilder headerVisible(boolean v0) {
        framedPanel.setHeaderVisible(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setHeading(java.lang.String)
     */
    public FramedPanelBuilder heading(java.lang.String v0) {
        framedPanel.setHeading(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setHeading(com.google.gwt.safehtml.shared.SafeHtml)
     */
    public FramedPanelBuilder heading(com.google.gwt.safehtml.shared.SafeHtml v0) {
        framedPanel.setHeading(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setHeight(java.lang.String)
     */
    public FramedPanelBuilder height(java.lang.String v0) {
        framedPanel.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setHeight(int)
     */
    public FramedPanelBuilder height(int v0) {
        framedPanel.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setHideCollapseTool(boolean)
     */
    public FramedPanelBuilder hideCollapseTool(boolean v0) {
        framedPanel.setHideCollapseTool(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setHideMode(com.sencha.gxt.core.client.Style.HideMode)
     */
    public FramedPanelBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        framedPanel.setHideMode(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setId(java.lang.String)
     */
    public FramedPanelBuilder id(java.lang.String v0) {
        framedPanel.setId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setItemId(java.lang.String)
     */
    public FramedPanelBuilder itemId(java.lang.String v0) {
        framedPanel.setItemId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setLayoutData(java.lang.Object)
     */
    public FramedPanelBuilder layoutData(java.lang.Object v0) {
        framedPanel.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setMessages(com.sencha.gxt.widget.core.client.ContentPanel.ContentPanelMessages)
     */
    public FramedPanelBuilder messages(com.sencha.gxt.widget.core.client.ContentPanel.ContentPanelMessages v0) {
        framedPanel.setMessages(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setMinButtonWidth(int)
     */
    public FramedPanelBuilder minButtonWidth(int v0) {
        framedPanel.setMinButtonWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setPagePosition(int, int)
     */
    public FramedPanelBuilder pagePosition(int v0, int v1) {
        framedPanel.setPagePosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setPixelSize(int, int)
     */
    public FramedPanelBuilder pixelSize(int v0, int v1) {
        framedPanel.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setPosition(int, int)
     */
    public FramedPanelBuilder position(int v0, int v1) {
        framedPanel.setPosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setResize(boolean)
     */
    public FramedPanelBuilder resize(boolean v0) {
        framedPanel.setResize(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setShadow(boolean)
     */
    public FramedPanelBuilder shadow(boolean v0) {
        framedPanel.setShadow(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setShadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition)
     */
    public FramedPanelBuilder shadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition v0) {
        framedPanel.setShadowPosition(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setSize(java.lang.String, java.lang.String)
     */
    public FramedPanelBuilder size(java.lang.String v0, java.lang.String v1) {
        framedPanel.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setStateId(java.lang.String)
     */
    public FramedPanelBuilder stateId(java.lang.String v0) {
        framedPanel.setStateId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setStateful(boolean)
     */
    public FramedPanelBuilder stateful(boolean v0) {
        framedPanel.setStateful(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setStyleDependentName(java.lang.String, boolean)
     */
    public FramedPanelBuilder styleDependentName(java.lang.String v0, boolean v1) {
        framedPanel.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setStyleName(java.lang.String)
     */
    public FramedPanelBuilder styleName(java.lang.String v0) {
        framedPanel.setStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setStyleName(java.lang.String, boolean)
     */
    public FramedPanelBuilder styleName(java.lang.String v0, boolean v1) {
        framedPanel.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setStylePrimaryName(java.lang.String)
     */
    public FramedPanelBuilder stylePrimaryName(java.lang.String v0) {
        framedPanel.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setTabIndex(int)
     */
    public FramedPanelBuilder tabIndex(int v0) {
        framedPanel.setTabIndex(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setTitle(java.lang.String)
     */
    public FramedPanelBuilder title(java.lang.String v0) {
        framedPanel.setTitle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setTitleCollapse(boolean)
     */
    public FramedPanelBuilder titleCollapse(boolean v0) {
        framedPanel.setTitleCollapse(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setToolTip(java.lang.String)
     */
    public FramedPanelBuilder toolTip(java.lang.String v0) {
        framedPanel.setToolTip(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setToolTip(com.google.gwt.safehtml.shared.SafeHtml)
     */
    public FramedPanelBuilder toolTip(com.google.gwt.safehtml.shared.SafeHtml v0) {
        framedPanel.setToolTip(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setToolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig)
     */
    public FramedPanelBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        framedPanel.setToolTipConfig(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setVisible(boolean)
     */
    public FramedPanelBuilder visible(boolean v0) {
        framedPanel.setVisible(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setWidget(com.google.gwt.user.client.ui.Widget)
     */
    public FramedPanelBuilder widget(com.google.gwt.user.client.ui.Widget v0) {
        framedPanel.setWidget(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setWidget(com.google.gwt.user.client.ui.IsWidget)
     */
    public FramedPanelBuilder widget(com.google.gwt.user.client.ui.IsWidget v0) {
        framedPanel.setWidget(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setWidth(java.lang.String)
     */
    public FramedPanelBuilder width(java.lang.String v0) {
        framedPanel.setWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.FramedPanel#setWidth(int)
     */
    public FramedPanelBuilder width(int v0) {
        framedPanel.setWidth(v0);
        return this;
    }
}
