package biz.freshcode.learn.gwt2.common.client.builder.gxt;

import com.sencha.gxt.widget.core.client.TabItemConfig;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.widget.core.client.TabItemConfig
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt2.common.client.builder.BeanBuilder(TabItemConfig.class)
public class TabItemConfigBuilder extends biz.freshcode.learn.gwt2.common.client.builder.Construct.Parent<TabItemConfigBuilder> {
    public final TabItemConfig tabItemConfig;

    public TabItemConfigBuilder(TabItemConfig v) {
        tabItemConfig = v;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.TabItemConfig#TabItemConfig()
     */
    public TabItemConfigBuilder() {
        this(new TabItemConfig());
    }

    /**
     * @see com.sencha.gxt.widget.core.client.TabItemConfig#TabItemConfig(java.lang.String)
     */
    public TabItemConfigBuilder(java.lang.String v0) {
        this(new TabItemConfig(v0));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.TabItemConfig#TabItemConfig(java.lang.String, boolean)
     */
    public TabItemConfigBuilder(java.lang.String v0, boolean v1) {
        this(new TabItemConfig(v0, v1));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.TabItemConfig#setClosable(boolean)
     */
    public TabItemConfigBuilder closable(boolean v0) {
        tabItemConfig.setClosable(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.TabItemConfig#setContent(java.lang.String)
     */
    public TabItemConfigBuilder content(java.lang.String v0) {
        tabItemConfig.setContent(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.TabItemConfig#setContent(com.google.gwt.safehtml.shared.SafeHtml)
     */
    public TabItemConfigBuilder content(com.google.gwt.safehtml.shared.SafeHtml v0) {
        tabItemConfig.setContent(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.TabItemConfig#setEnabled(boolean)
     */
    public TabItemConfigBuilder enabled(boolean v0) {
        tabItemConfig.setEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.TabItemConfig#setHTML(java.lang.String)
     */
    public TabItemConfigBuilder hTML(java.lang.String v0) {
        tabItemConfig.setHTML(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.TabItemConfig#setHTML(com.google.gwt.safehtml.shared.SafeHtml)
     */
    public TabItemConfigBuilder hTML(com.google.gwt.safehtml.shared.SafeHtml v0) {
        tabItemConfig.setHTML(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.TabItemConfig#setIcon(com.google.gwt.resources.client.ImageResource)
     */
    public TabItemConfigBuilder icon(com.google.gwt.resources.client.ImageResource v0) {
        tabItemConfig.setIcon(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.TabItemConfig#setText(java.lang.String)
     */
    public TabItemConfigBuilder text(java.lang.String v0) {
        tabItemConfig.setText(v0);
        return this;
    }
}
