package biz.freshcode.learn.gwt.mod1.client.builder.gxt.container;

import com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt.mod1.client.builder.BeanBuilder(HBoxLayoutContainer.class)
public class HBoxLayoutContainerBuilder extends biz.freshcode.learn.gwt.mod1.client.builder.Construct.Parent<HBoxLayoutContainerBuilder> {
    public final HBoxLayoutContainer hBoxLayoutContainer;

    public HBoxLayoutContainerBuilder(HBoxLayoutContainer v) {
        hBoxLayoutContainer = v;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#HBoxLayoutContainer(com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer.HBoxLayoutAlign)
     */
    public HBoxLayoutContainerBuilder(com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer.HBoxLayoutAlign v0) {
        this(new HBoxLayoutContainer(v0));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#HBoxLayoutContainer(com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer.HBoxLayoutContainerAppearance)
     */
    public HBoxLayoutContainerBuilder(com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer.HBoxLayoutContainerAppearance v0) {
        this(new HBoxLayoutContainer(v0));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#HBoxLayoutContainer()
     */
    public HBoxLayoutContainerBuilder() {
        this(new HBoxLayoutContainer());
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#add(com.google.gwt.user.client.ui.Widget)
     */
    public HBoxLayoutContainerBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        hBoxLayoutContainer.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public HBoxLayoutContainerBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        hBoxLayoutContainer.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#add(com.google.gwt.user.client.ui.IsWidget, com.sencha.gxt.widget.core.client.container.BoxLayoutContainer.BoxLayoutData)
     */
    public HBoxLayoutContainerBuilder add(com.google.gwt.user.client.ui.IsWidget v0, com.sencha.gxt.widget.core.client.container.BoxLayoutContainer.BoxLayoutData v1) {
        hBoxLayoutContainer.add(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#addStyleDependentName(java.lang.String)
     */
    public HBoxLayoutContainerBuilder addStyleDependentName(java.lang.String v0) {
        hBoxLayoutContainer.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#addStyleName(java.lang.String)
     */
    public HBoxLayoutContainerBuilder addStyleName(java.lang.String v0) {
        hBoxLayoutContainer.addStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#addStyleOnOver(com.google.gwt.dom.client.Element, java.lang.String)
     */
    public HBoxLayoutContainerBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        hBoxLayoutContainer.addStyleOnOver(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setAdjustForFlexRemainder(boolean)
     */
    public HBoxLayoutContainerBuilder adjustForFlexRemainder(boolean v0) {
        hBoxLayoutContainer.setAdjustForFlexRemainder(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setAllowTextSelection(boolean)
     */
    public HBoxLayoutContainerBuilder allowTextSelection(boolean v0) {
        hBoxLayoutContainer.setAllowTextSelection(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setBorders(boolean)
     */
    public HBoxLayoutContainerBuilder borders(boolean v0) {
        hBoxLayoutContainer.setBorders(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setBounds(com.sencha.gxt.core.client.util.Rectangle)
     */
    public HBoxLayoutContainerBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        hBoxLayoutContainer.setBounds(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setBounds(int, int, int, int)
     */
    public HBoxLayoutContainerBuilder bounds(int v0, int v1, int v2, int v3) {
        hBoxLayoutContainer.setBounds(v0, v1, v2, v3);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setContextMenu(com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public HBoxLayoutContainerBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        hBoxLayoutContainer.setContextMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setData(java.lang.String, java.lang.Object)
     */
    public HBoxLayoutContainerBuilder data(java.lang.String v0, java.lang.Object v1) {
        hBoxLayoutContainer.setData(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setDeferHeight(boolean)
     */
    public HBoxLayoutContainerBuilder deferHeight(boolean v0) {
        hBoxLayoutContainer.setDeferHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setEnableOverflow(boolean)
     */
    public HBoxLayoutContainerBuilder enableOverflow(boolean v0) {
        hBoxLayoutContainer.setEnableOverflow(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setEnabled(boolean)
     */
    public HBoxLayoutContainerBuilder enabled(boolean v0) {
        hBoxLayoutContainer.setEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setHBoxLayoutAlign(com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer.HBoxLayoutAlign)
     */
    public HBoxLayoutContainerBuilder hBoxLayoutAlign(com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer.HBoxLayoutAlign v0) {
        hBoxLayoutContainer.setHBoxLayoutAlign(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setHeight(java.lang.String)
     */
    public HBoxLayoutContainerBuilder height(java.lang.String v0) {
        hBoxLayoutContainer.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setHeight(int)
     */
    public HBoxLayoutContainerBuilder height(int v0) {
        hBoxLayoutContainer.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setHideMode(com.sencha.gxt.core.client.Style.HideMode)
     */
    public HBoxLayoutContainerBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        hBoxLayoutContainer.setHideMode(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setId(java.lang.String)
     */
    public HBoxLayoutContainerBuilder id(java.lang.String v0) {
        hBoxLayoutContainer.setId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setItemId(java.lang.String)
     */
    public HBoxLayoutContainerBuilder itemId(java.lang.String v0) {
        hBoxLayoutContainer.setItemId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setLayoutData(java.lang.Object)
     */
    public HBoxLayoutContainerBuilder layoutData(java.lang.Object v0) {
        hBoxLayoutContainer.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setPack(com.sencha.gxt.widget.core.client.container.BoxLayoutContainer.BoxLayoutPack)
     */
    public HBoxLayoutContainerBuilder pack(com.sencha.gxt.widget.core.client.container.BoxLayoutContainer.BoxLayoutPack v0) {
        hBoxLayoutContainer.setPack(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setPadding(com.sencha.gxt.core.client.util.Padding)
     */
    public HBoxLayoutContainerBuilder padding(com.sencha.gxt.core.client.util.Padding v0) {
        hBoxLayoutContainer.setPadding(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setPagePosition(int, int)
     */
    public HBoxLayoutContainerBuilder pagePosition(int v0, int v1) {
        hBoxLayoutContainer.setPagePosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setPixelSize(int, int)
     */
    public HBoxLayoutContainerBuilder pixelSize(int v0, int v1) {
        hBoxLayoutContainer.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setPosition(int, int)
     */
    public HBoxLayoutContainerBuilder position(int v0, int v1) {
        hBoxLayoutContainer.setPosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setScrollOffset(int)
     */
    public HBoxLayoutContainerBuilder scrollOffset(int v0) {
        hBoxLayoutContainer.setScrollOffset(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setShadow(boolean)
     */
    public HBoxLayoutContainerBuilder shadow(boolean v0) {
        hBoxLayoutContainer.setShadow(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setShadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition)
     */
    public HBoxLayoutContainerBuilder shadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition v0) {
        hBoxLayoutContainer.setShadowPosition(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setSize(java.lang.String, java.lang.String)
     */
    public HBoxLayoutContainerBuilder size(java.lang.String v0, java.lang.String v1) {
        hBoxLayoutContainer.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setStateId(java.lang.String)
     */
    public HBoxLayoutContainerBuilder stateId(java.lang.String v0) {
        hBoxLayoutContainer.setStateId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setStateful(boolean)
     */
    public HBoxLayoutContainerBuilder stateful(boolean v0) {
        hBoxLayoutContainer.setStateful(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setStyleDependentName(java.lang.String, boolean)
     */
    public HBoxLayoutContainerBuilder styleDependentName(java.lang.String v0, boolean v1) {
        hBoxLayoutContainer.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setStyleName(java.lang.String)
     */
    public HBoxLayoutContainerBuilder styleName(java.lang.String v0) {
        hBoxLayoutContainer.setStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setStyleName(java.lang.String, boolean)
     */
    public HBoxLayoutContainerBuilder styleName(java.lang.String v0, boolean v1) {
        hBoxLayoutContainer.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setStylePrimaryName(java.lang.String)
     */
    public HBoxLayoutContainerBuilder stylePrimaryName(java.lang.String v0) {
        hBoxLayoutContainer.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setTabIndex(int)
     */
    public HBoxLayoutContainerBuilder tabIndex(int v0) {
        hBoxLayoutContainer.setTabIndex(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setTitle(java.lang.String)
     */
    public HBoxLayoutContainerBuilder title(java.lang.String v0) {
        hBoxLayoutContainer.setTitle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setToolTip(java.lang.String)
     */
    public HBoxLayoutContainerBuilder toolTip(java.lang.String v0) {
        hBoxLayoutContainer.setToolTip(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setToolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig)
     */
    public HBoxLayoutContainerBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        hBoxLayoutContainer.setToolTipConfig(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setVisible(boolean)
     */
    public HBoxLayoutContainerBuilder visible(boolean v0) {
        hBoxLayoutContainer.setVisible(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setWidth(java.lang.String)
     */
    public HBoxLayoutContainerBuilder width(java.lang.String v0) {
        hBoxLayoutContainer.setWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer#setWidth(int)
     */
    public HBoxLayoutContainerBuilder width(int v0) {
        hBoxLayoutContainer.setWidth(v0);
        return this;
    }
}
