package biz.freshcode.learn.gwt2.common.client.builder.gxt.chart.series;

import com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt2.common.client.builder.BeanBuilder(SeriesToolTipConfig.class)
public class SeriesToolTipConfigBuilder<M> extends biz.freshcode.learn.gwt2.common.client.builder.Construct.Parent<SeriesToolTipConfigBuilder<M>> {
    public final SeriesToolTipConfig<M> seriesToolTipConfig;

    public SeriesToolTipConfigBuilder(SeriesToolTipConfig<M> v) {
        seriesToolTipConfig = v;
    }

    public SeriesToolTipConfigBuilder() {
        this(new SeriesToolTipConfig<M>());
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setAnchor(com.sencha.gxt.core.client.Style.Side)
     */
    public SeriesToolTipConfigBuilder<M> anchor(com.sencha.gxt.core.client.Style.Side v0) {
        seriesToolTipConfig.setAnchor(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setAnchorArrow(boolean)
     */
    public SeriesToolTipConfigBuilder<M> anchorArrow(boolean v0) {
        seriesToolTipConfig.setAnchorArrow(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setAnchorOffset(int)
     */
    public SeriesToolTipConfigBuilder<M> anchorOffset(int v0) {
        seriesToolTipConfig.setAnchorOffset(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setAnchorToTarget(boolean)
     */
    public SeriesToolTipConfigBuilder<M> anchorToTarget(boolean v0) {
        seriesToolTipConfig.setAnchorToTarget(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setAutoHide(boolean)
     */
    public SeriesToolTipConfigBuilder<M> autoHide(boolean v0) {
        seriesToolTipConfig.setAutoHide(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setBody(java.lang.String)
     */
    public SeriesToolTipConfigBuilder<M> body(java.lang.String v0) {
        seriesToolTipConfig.setBody(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setBody(com.google.gwt.safehtml.shared.SafeHtml)
     */
    public SeriesToolTipConfigBuilder<M> body(com.google.gwt.safehtml.shared.SafeHtml v0) {
        seriesToolTipConfig.setBody(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setCloseable(boolean)
     */
    public SeriesToolTipConfigBuilder<M> closeable(boolean v0) {
        seriesToolTipConfig.setCloseable(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setData(java.lang.Object)
     */
    public SeriesToolTipConfigBuilder<M> data(java.lang.Object v0) {
        seriesToolTipConfig.setData(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setDismissDelay(int)
     */
    public SeriesToolTipConfigBuilder<M> dismissDelay(int v0) {
        seriesToolTipConfig.setDismissDelay(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setEnabled(boolean)
     */
    public SeriesToolTipConfigBuilder<M> enabled(boolean v0) {
        seriesToolTipConfig.setEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setHideDelay(int)
     */
    public SeriesToolTipConfigBuilder<M> hideDelay(int v0) {
        seriesToolTipConfig.setHideDelay(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setLabelProvider(com.sencha.gxt.chart.client.chart.series.SeriesLabelProvider)
     */
    public SeriesToolTipConfigBuilder<M> labelProvider(com.sencha.gxt.chart.client.chart.series.SeriesLabelProvider<M> v0) {
        seriesToolTipConfig.setLabelProvider(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setMaxWidth(int)
     */
    public SeriesToolTipConfigBuilder<M> maxWidth(int v0) {
        seriesToolTipConfig.setMaxWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setMinWidth(int)
     */
    public SeriesToolTipConfigBuilder<M> minWidth(int v0) {
        seriesToolTipConfig.setMinWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setMouseOffsetX(int)
     */
    public SeriesToolTipConfigBuilder<M> mouseOffsetX(int v0) {
        seriesToolTipConfig.setMouseOffsetX(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setMouseOffsetY(int)
     */
    public SeriesToolTipConfigBuilder<M> mouseOffsetY(int v0) {
        seriesToolTipConfig.setMouseOffsetY(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setNumberFormatProvider(com.google.gwt.i18n.client.NumberFormat)
     */
    public SeriesToolTipConfigBuilder<M> numberFormatProvider(com.google.gwt.i18n.client.NumberFormat v0) {
        seriesToolTipConfig.setNumberFormatProvider(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setRenderer(com.sencha.gxt.widget.core.client.tips.ToolTipConfig.ToolTipRenderer)
     */
    public SeriesToolTipConfigBuilder<M> renderer(com.sencha.gxt.widget.core.client.tips.ToolTipConfig.ToolTipRenderer<?> v0) {
        seriesToolTipConfig.setRenderer(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setShowDelay(int)
     */
    public SeriesToolTipConfigBuilder<M> showDelay(int v0) {
        seriesToolTipConfig.setShowDelay(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setTitle(java.lang.String)
     */
    public SeriesToolTipConfigBuilder<M> title(java.lang.String v0) {
        seriesToolTipConfig.setTitle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setTitle(com.google.gwt.safehtml.shared.SafeHtml)
     */
    public SeriesToolTipConfigBuilder<M> title(com.google.gwt.safehtml.shared.SafeHtml v0) {
        seriesToolTipConfig.setTitle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setTrackMouse(boolean)
     */
    public SeriesToolTipConfigBuilder<M> trackMouse(boolean v0) {
        seriesToolTipConfig.setTrackMouse(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.chart.client.chart.series.SeriesToolTipConfig#setValueProvider(com.sencha.gxt.core.client.ValueProvider, com.sencha.gxt.data.shared.LabelProvider)
     */
    public <V> SeriesToolTipConfigBuilder<M> valueProvider(com.sencha.gxt.core.client.ValueProvider<? super M, V> v0, com.sencha.gxt.data.shared.LabelProvider<? super V> v1) {
        seriesToolTipConfig.setValueProvider(v0, v1);
        return this;
    }
}
