package biz.freshcode.learn.gwt.common.client.builder.gxt.form;

import com.sencha.gxt.widget.core.client.form.FieldLabel;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.widget.core.client.form.FieldLabel
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt.common.client.builder.BeanBuilder(FieldLabel.class)
public class FieldLabelBuilder extends biz.freshcode.learn.gwt.common.client.builder.Construct.Parent<FieldLabelBuilder> {
    public final FieldLabel fieldLabel;

    public FieldLabelBuilder(FieldLabel v) {
        fieldLabel = v;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#FieldLabel(com.google.gwt.user.client.ui.IsWidget, java.lang.String, com.sencha.gxt.widget.core.client.form.FieldLabel.FieldLabelAppearance)
     */
    public FieldLabelBuilder(com.google.gwt.user.client.ui.IsWidget v0, java.lang.String v1, com.sencha.gxt.widget.core.client.form.FieldLabel.FieldLabelAppearance v2) {
        this(new FieldLabel(v0, v1, v2));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#FieldLabel(com.google.gwt.user.client.ui.IsWidget, java.lang.String)
     */
    public FieldLabelBuilder(com.google.gwt.user.client.ui.IsWidget v0, java.lang.String v1) {
        this(new FieldLabel(v0, v1));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#FieldLabel(com.google.gwt.user.client.ui.Widget, com.sencha.gxt.widget.core.client.form.FieldLabel.FieldLabelAppearance)
     */
    public FieldLabelBuilder(com.google.gwt.user.client.ui.Widget v0, com.sencha.gxt.widget.core.client.form.FieldLabel.FieldLabelAppearance v1) {
        this(new FieldLabel(v0, v1));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#FieldLabel()
     */
    public FieldLabelBuilder() {
        this(new FieldLabel());
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#FieldLabel(com.google.gwt.user.client.ui.IsWidget)
     */
    public FieldLabelBuilder(com.google.gwt.user.client.ui.IsWidget v0) {
        this(new FieldLabel(v0));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#FieldLabel(com.google.gwt.user.client.ui.IsWidget, com.sencha.gxt.widget.core.client.form.FieldLabel.FieldLabelAppearance)
     */
    public FieldLabelBuilder(com.google.gwt.user.client.ui.IsWidget v0, com.sencha.gxt.widget.core.client.form.FieldLabel.FieldLabelAppearance v1) {
        this(new FieldLabel(v0, v1));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#add(com.google.gwt.user.client.ui.Widget)
     */
    public FieldLabelBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        fieldLabel.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public FieldLabelBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        fieldLabel.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#add(com.google.gwt.user.client.ui.Widget, com.sencha.gxt.widget.core.client.container.MarginData)
     */
    public FieldLabelBuilder add(com.google.gwt.user.client.ui.Widget v0, com.sencha.gxt.widget.core.client.container.MarginData v1) {
        fieldLabel.add(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#addStyleDependentName(java.lang.String)
     */
    public FieldLabelBuilder addStyleDependentName(java.lang.String v0) {
        fieldLabel.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#addStyleName(java.lang.String)
     */
    public FieldLabelBuilder addStyleName(java.lang.String v0) {
        fieldLabel.addStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#addStyleOnOver(com.google.gwt.dom.client.Element, java.lang.String)
     */
    public FieldLabelBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        fieldLabel.addStyleOnOver(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setAllowTextSelection(boolean)
     */
    public FieldLabelBuilder allowTextSelection(boolean v0) {
        fieldLabel.setAllowTextSelection(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setBorders(boolean)
     */
    public FieldLabelBuilder borders(boolean v0) {
        fieldLabel.setBorders(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setBounds(com.sencha.gxt.core.client.util.Rectangle)
     */
    public FieldLabelBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        fieldLabel.setBounds(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setBounds(int, int, int, int)
     */
    public FieldLabelBuilder bounds(int v0, int v1, int v2, int v3) {
        fieldLabel.setBounds(v0, v1, v2, v3);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setContextMenu(com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public FieldLabelBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        fieldLabel.setContextMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setData(java.lang.String, java.lang.Object)
     */
    public FieldLabelBuilder data(java.lang.String v0, java.lang.Object v1) {
        fieldLabel.setData(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setDeferHeight(boolean)
     */
    public FieldLabelBuilder deferHeight(boolean v0) {
        fieldLabel.setDeferHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setEnabled(boolean)
     */
    public FieldLabelBuilder enabled(boolean v0) {
        fieldLabel.setEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setHTML(java.lang.String)
     */
    public FieldLabelBuilder hTML(java.lang.String v0) {
        fieldLabel.setHTML(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setHTML(com.google.gwt.safehtml.shared.SafeHtml)
     */
    public FieldLabelBuilder hTML(com.google.gwt.safehtml.shared.SafeHtml v0) {
        fieldLabel.setHTML(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setHeight(java.lang.String)
     */
    public FieldLabelBuilder height(java.lang.String v0) {
        fieldLabel.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setHeight(int)
     */
    public FieldLabelBuilder height(int v0) {
        fieldLabel.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setHideMode(com.sencha.gxt.core.client.Style.HideMode)
     */
    public FieldLabelBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        fieldLabel.setHideMode(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setId(java.lang.String)
     */
    public FieldLabelBuilder id(java.lang.String v0) {
        fieldLabel.setId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setItemId(java.lang.String)
     */
    public FieldLabelBuilder itemId(java.lang.String v0) {
        fieldLabel.setItemId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setLabelAlign(com.sencha.gxt.widget.core.client.form.FormPanel.LabelAlign)
     */
    public FieldLabelBuilder labelAlign(com.sencha.gxt.widget.core.client.form.FormPanel.LabelAlign v0) {
        fieldLabel.setLabelAlign(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setLabelPad(int)
     */
    public FieldLabelBuilder labelPad(int v0) {
        fieldLabel.setLabelPad(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setLabelSeparator(java.lang.String)
     */
    public FieldLabelBuilder labelSeparator(java.lang.String v0) {
        fieldLabel.setLabelSeparator(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setLabelWidth(int)
     */
    public FieldLabelBuilder labelWidth(int v0) {
        fieldLabel.setLabelWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setLabelWordWrap(boolean)
     */
    public FieldLabelBuilder labelWordWrap(boolean v0) {
        fieldLabel.setLabelWordWrap(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setLayoutData(java.lang.Object)
     */
    public FieldLabelBuilder layoutData(java.lang.Object v0) {
        fieldLabel.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setPagePosition(int, int)
     */
    public FieldLabelBuilder pagePosition(int v0, int v1) {
        fieldLabel.setPagePosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setPixelSize(int, int)
     */
    public FieldLabelBuilder pixelSize(int v0, int v1) {
        fieldLabel.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setPosition(int, int)
     */
    public FieldLabelBuilder position(int v0, int v1) {
        fieldLabel.setPosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setResize(boolean)
     */
    public FieldLabelBuilder resize(boolean v0) {
        fieldLabel.setResize(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setShadow(boolean)
     */
    public FieldLabelBuilder shadow(boolean v0) {
        fieldLabel.setShadow(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setShadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition)
     */
    public FieldLabelBuilder shadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition v0) {
        fieldLabel.setShadowPosition(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setSize(java.lang.String, java.lang.String)
     */
    public FieldLabelBuilder size(java.lang.String v0, java.lang.String v1) {
        fieldLabel.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setStateId(java.lang.String)
     */
    public FieldLabelBuilder stateId(java.lang.String v0) {
        fieldLabel.setStateId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setStateful(boolean)
     */
    public FieldLabelBuilder stateful(boolean v0) {
        fieldLabel.setStateful(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setStyleDependentName(java.lang.String, boolean)
     */
    public FieldLabelBuilder styleDependentName(java.lang.String v0, boolean v1) {
        fieldLabel.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setStyleName(java.lang.String)
     */
    public FieldLabelBuilder styleName(java.lang.String v0) {
        fieldLabel.setStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setStyleName(java.lang.String, boolean)
     */
    public FieldLabelBuilder styleName(java.lang.String v0, boolean v1) {
        fieldLabel.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setStylePrimaryName(java.lang.String)
     */
    public FieldLabelBuilder stylePrimaryName(java.lang.String v0) {
        fieldLabel.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setTabIndex(int)
     */
    public FieldLabelBuilder tabIndex(int v0) {
        fieldLabel.setTabIndex(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setText(java.lang.String)
     */
    public FieldLabelBuilder text(java.lang.String v0) {
        fieldLabel.setText(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setTitle(java.lang.String)
     */
    public FieldLabelBuilder title(java.lang.String v0) {
        fieldLabel.setTitle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setToolTip(java.lang.String)
     */
    public FieldLabelBuilder toolTip(java.lang.String v0) {
        fieldLabel.setToolTip(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setToolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig)
     */
    public FieldLabelBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        fieldLabel.setToolTipConfig(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setVisible(boolean)
     */
    public FieldLabelBuilder visible(boolean v0) {
        fieldLabel.setVisible(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setWidget(com.google.gwt.user.client.ui.Widget)
     */
    public FieldLabelBuilder widget(com.google.gwt.user.client.ui.Widget v0) {
        fieldLabel.setWidget(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setWidget(com.google.gwt.user.client.ui.IsWidget)
     */
    public FieldLabelBuilder widget(com.google.gwt.user.client.ui.IsWidget v0) {
        fieldLabel.setWidget(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setWidth(java.lang.String)
     */
    public FieldLabelBuilder width(java.lang.String v0) {
        fieldLabel.setWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FieldLabel#setWidth(int)
     */
    public FieldLabelBuilder width(int v0) {
        fieldLabel.setWidth(v0);
        return this;
    }
}
