package biz.freshcode.learn.gwt_bootstrap.client.builder.org.gwtbootstrap3.client.ui;

import org.gwtbootstrap3.client.ui.Anchor;

/**
 * Generated by BuilderGenerator
 *
 * @see org.gwtbootstrap3.client.ui.Anchor
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt_bootstrap.client.builder.BeanBuilder(Anchor.class)
public class AnchorBuilder extends biz.freshcode.learn.gwt_bootstrap.client.builder.Construct.Parent<AnchorBuilder> {
    public final Anchor anchor;

    public AnchorBuilder(Anchor v) {
        anchor = v;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#Anchor(java.lang.String, java.lang.String)
     */
    public AnchorBuilder(java.lang.String v0, java.lang.String v1) {
        this(new Anchor(v0, v1));
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#Anchor(java.lang.String)
     */
    public AnchorBuilder(java.lang.String v0) {
        this(new Anchor(v0));
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#Anchor()
     */
    public AnchorBuilder() {
        this(new Anchor());
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#add(com.google.gwt.user.client.ui.Widget)
     */
    public AnchorBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        anchor.add(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public AnchorBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        anchor.add(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#addStyleDependentName(java.lang.String)
     */
    public AnchorBuilder addStyleDependentName(java.lang.String v0) {
        anchor.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#addStyleName(java.lang.String)
     */
    public AnchorBuilder addStyleName(java.lang.String v0) {
        anchor.addStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setAccessKey(char)
     */
    public AnchorBuilder accessKey(char v0) {
        anchor.setAccessKey(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setColor(java.lang.String)
     */
    public AnchorBuilder color(java.lang.String v0) {
        anchor.setColor(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setDataParent(java.lang.String)
     */
    public AnchorBuilder dataParent(java.lang.String v0) {
        anchor.setDataParent(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setDataTarget(java.lang.String)
     */
    public AnchorBuilder dataTarget(java.lang.String v0) {
        anchor.setDataTarget(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setDataTargetWidget(com.google.gwt.user.client.ui.Widget)
     */
    public AnchorBuilder dataTargetWidget(com.google.gwt.user.client.ui.Widget v0) {
        anchor.setDataTargetWidget(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setDataTargetWidgets(java.util.List)
     */
    public AnchorBuilder dataTargetWidgets(java.util.List<com.google.gwt.user.client.ui.Widget> v0) {
        anchor.setDataTargetWidgets(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setDataToggle(org.gwtbootstrap3.client.ui.constants.Toggle)
     */
    public AnchorBuilder dataToggle(org.gwtbootstrap3.client.ui.constants.Toggle v0) {
        anchor.setDataToggle(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setEnabled(boolean)
     */
    public AnchorBuilder enabled(boolean v0) {
        anchor.setEnabled(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setFocus(boolean)
     */
    public AnchorBuilder focus(boolean v0) {
        anchor.setFocus(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setHTML(java.lang.String)
     */
    public AnchorBuilder hTML(java.lang.String v0) {
        anchor.setHTML(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setHeight(java.lang.String)
     */
    public AnchorBuilder height(java.lang.String v0) {
        anchor.setHeight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setHiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public AnchorBuilder hiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        anchor.setHiddenOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setHref(java.lang.String)
     */
    public AnchorBuilder href(java.lang.String v0) {
        anchor.setHref(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setIcon(org.gwtbootstrap3.client.ui.constants.IconType)
     */
    public AnchorBuilder icon(org.gwtbootstrap3.client.ui.constants.IconType v0) {
        anchor.setIcon(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setIconBordered(boolean)
     */
    public AnchorBuilder iconBordered(boolean v0) {
        anchor.setIconBordered(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setIconFixedWidth(boolean)
     */
    public AnchorBuilder iconFixedWidth(boolean v0) {
        anchor.setIconFixedWidth(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setIconFlip(org.gwtbootstrap3.client.ui.constants.IconFlip)
     */
    public AnchorBuilder iconFlip(org.gwtbootstrap3.client.ui.constants.IconFlip v0) {
        anchor.setIconFlip(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setIconLight(boolean)
     */
    public AnchorBuilder iconLight(boolean v0) {
        anchor.setIconLight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setIconMuted(boolean)
     */
    public AnchorBuilder iconMuted(boolean v0) {
        anchor.setIconMuted(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setIconPosition(org.gwtbootstrap3.client.ui.constants.IconPosition)
     */
    public AnchorBuilder iconPosition(org.gwtbootstrap3.client.ui.constants.IconPosition v0) {
        anchor.setIconPosition(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setIconRotate(org.gwtbootstrap3.client.ui.constants.IconRotate)
     */
    public AnchorBuilder iconRotate(org.gwtbootstrap3.client.ui.constants.IconRotate v0) {
        anchor.setIconRotate(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setIconSize(org.gwtbootstrap3.client.ui.constants.IconSize)
     */
    public AnchorBuilder iconSize(org.gwtbootstrap3.client.ui.constants.IconSize v0) {
        anchor.setIconSize(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setIconSpin(boolean)
     */
    public AnchorBuilder iconSpin(boolean v0) {
        anchor.setIconSpin(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setId(java.lang.String)
     */
    public AnchorBuilder id(java.lang.String v0) {
        anchor.setId(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setLayoutData(java.lang.Object)
     */
    public AnchorBuilder layoutData(java.lang.Object v0) {
        anchor.setLayoutData(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setMarginBottom(double)
     */
    public AnchorBuilder marginBottom(double v0) {
        anchor.setMarginBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setMarginLeft(double)
     */
    public AnchorBuilder marginLeft(double v0) {
        anchor.setMarginLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setMarginRight(double)
     */
    public AnchorBuilder marginRight(double v0) {
        anchor.setMarginRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setMarginTop(double)
     */
    public AnchorBuilder marginTop(double v0) {
        anchor.setMarginTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setPaddingBottom(double)
     */
    public AnchorBuilder paddingBottom(double v0) {
        anchor.setPaddingBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setPaddingLeft(double)
     */
    public AnchorBuilder paddingLeft(double v0) {
        anchor.setPaddingLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setPaddingRight(double)
     */
    public AnchorBuilder paddingRight(double v0) {
        anchor.setPaddingRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setPaddingTop(double)
     */
    public AnchorBuilder paddingTop(double v0) {
        anchor.setPaddingTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setPixelSize(int, int)
     */
    public AnchorBuilder pixelSize(int v0, int v1) {
        anchor.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setPull(org.gwtbootstrap3.client.ui.constants.Pull)
     */
    public AnchorBuilder pull(org.gwtbootstrap3.client.ui.constants.Pull v0) {
        anchor.setPull(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setSize(java.lang.String, java.lang.String)
     */
    public AnchorBuilder size(java.lang.String v0, java.lang.String v1) {
        anchor.setSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setStyleDependentName(java.lang.String, boolean)
     */
    public AnchorBuilder styleDependentName(java.lang.String v0, boolean v1) {
        anchor.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setStyleName(java.lang.String)
     */
    public AnchorBuilder styleName(java.lang.String v0) {
        anchor.setStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setStyleName(java.lang.String, boolean)
     */
    public AnchorBuilder styleName(java.lang.String v0, boolean v1) {
        anchor.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setStylePrimaryName(java.lang.String)
     */
    public AnchorBuilder stylePrimaryName(java.lang.String v0) {
        anchor.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setTabIndex(int)
     */
    public AnchorBuilder tabIndex(int v0) {
        anchor.setTabIndex(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setTarget(java.lang.String)
     */
    public AnchorBuilder target(java.lang.String v0) {
        anchor.setTarget(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setTargetHistoryToken(java.lang.String)
     */
    public AnchorBuilder targetHistoryToken(java.lang.String v0) {
        anchor.setTargetHistoryToken(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setText(java.lang.String)
     */
    public AnchorBuilder text(java.lang.String v0) {
        anchor.setText(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setTitle(java.lang.String)
     */
    public AnchorBuilder title(java.lang.String v0) {
        anchor.setTitle(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setVisible(boolean)
     */
    public AnchorBuilder visible(boolean v0) {
        anchor.setVisible(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setVisibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public AnchorBuilder visibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        anchor.setVisibleOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Anchor#setWidth(java.lang.String)
     */
    public AnchorBuilder width(java.lang.String v0) {
        anchor.setWidth(v0);
        return this;
    }
}
