package biz.freshcode.learn.gwt_bootstrap.client.builder.org.gwtbootstrap3.client.ui;

import org.gwtbootstrap3.client.ui.CarouselControl;

/**
 * Generated by BuilderGenerator
 *
 * @see org.gwtbootstrap3.client.ui.CarouselControl
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt_bootstrap.client.builder.BeanBuilder(CarouselControl.class)
public class CarouselControlBuilder extends biz.freshcode.learn.gwt_bootstrap.client.builder.Construct.Parent<CarouselControlBuilder> {
    public final CarouselControl carouselControl;

    public CarouselControlBuilder(CarouselControl v) {
        carouselControl = v;
    }

    public CarouselControlBuilder() {
        this(new CarouselControl());
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#add(com.google.gwt.user.client.ui.Widget)
     */
    public CarouselControlBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        carouselControl.add(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public CarouselControlBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        carouselControl.add(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#addStyleDependentName(java.lang.String)
     */
    public CarouselControlBuilder addStyleDependentName(java.lang.String v0) {
        carouselControl.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#addStyleName(java.lang.String)
     */
    public CarouselControlBuilder addStyleName(java.lang.String v0) {
        carouselControl.addStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setColor(java.lang.String)
     */
    public CarouselControlBuilder color(java.lang.String v0) {
        carouselControl.setColor(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setDataTarget(java.lang.String)
     */
    public CarouselControlBuilder dataTarget(java.lang.String v0) {
        carouselControl.setDataTarget(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setDataTargetWidget(com.google.gwt.user.client.ui.Widget)
     */
    public CarouselControlBuilder dataTargetWidget(com.google.gwt.user.client.ui.Widget v0) {
        carouselControl.setDataTargetWidget(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setDataTargetWidgets(java.util.List)
     */
    public CarouselControlBuilder dataTargetWidgets(java.util.List<com.google.gwt.user.client.ui.Widget> v0) {
        carouselControl.setDataTargetWidgets(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setHeight(java.lang.String)
     */
    public CarouselControlBuilder height(java.lang.String v0) {
        carouselControl.setHeight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setHiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public CarouselControlBuilder hiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        carouselControl.setHiddenOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setIconType(org.gwtbootstrap3.client.ui.constants.IconType)
     */
    public CarouselControlBuilder iconType(org.gwtbootstrap3.client.ui.constants.IconType v0) {
        carouselControl.setIconType(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setId(java.lang.String)
     */
    public CarouselControlBuilder id(java.lang.String v0) {
        carouselControl.setId(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setLayoutData(java.lang.Object)
     */
    public CarouselControlBuilder layoutData(java.lang.Object v0) {
        carouselControl.setLayoutData(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setMarginBottom(double)
     */
    public CarouselControlBuilder marginBottom(double v0) {
        carouselControl.setMarginBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setMarginLeft(double)
     */
    public CarouselControlBuilder marginLeft(double v0) {
        carouselControl.setMarginLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setMarginRight(double)
     */
    public CarouselControlBuilder marginRight(double v0) {
        carouselControl.setMarginRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setMarginTop(double)
     */
    public CarouselControlBuilder marginTop(double v0) {
        carouselControl.setMarginTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setNext(boolean)
     */
    public CarouselControlBuilder next(boolean v0) {
        carouselControl.setNext(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setPaddingBottom(double)
     */
    public CarouselControlBuilder paddingBottom(double v0) {
        carouselControl.setPaddingBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setPaddingLeft(double)
     */
    public CarouselControlBuilder paddingLeft(double v0) {
        carouselControl.setPaddingLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setPaddingRight(double)
     */
    public CarouselControlBuilder paddingRight(double v0) {
        carouselControl.setPaddingRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setPaddingTop(double)
     */
    public CarouselControlBuilder paddingTop(double v0) {
        carouselControl.setPaddingTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setPixelSize(int, int)
     */
    public CarouselControlBuilder pixelSize(int v0, int v1) {
        carouselControl.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setPrev(boolean)
     */
    public CarouselControlBuilder prev(boolean v0) {
        carouselControl.setPrev(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setPull(org.gwtbootstrap3.client.ui.constants.Pull)
     */
    public CarouselControlBuilder pull(org.gwtbootstrap3.client.ui.constants.Pull v0) {
        carouselControl.setPull(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setSize(java.lang.String, java.lang.String)
     */
    public CarouselControlBuilder size(java.lang.String v0, java.lang.String v1) {
        carouselControl.setSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setStyleDependentName(java.lang.String, boolean)
     */
    public CarouselControlBuilder styleDependentName(java.lang.String v0, boolean v1) {
        carouselControl.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setStyleName(java.lang.String)
     */
    public CarouselControlBuilder styleName(java.lang.String v0) {
        carouselControl.setStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setStyleName(java.lang.String, boolean)
     */
    public CarouselControlBuilder styleName(java.lang.String v0, boolean v1) {
        carouselControl.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setStylePrimaryName(java.lang.String)
     */
    public CarouselControlBuilder stylePrimaryName(java.lang.String v0) {
        carouselControl.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setTitle(java.lang.String)
     */
    public CarouselControlBuilder title(java.lang.String v0) {
        carouselControl.setTitle(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setVisible(boolean)
     */
    public CarouselControlBuilder visible(boolean v0) {
        carouselControl.setVisible(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setVisibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public CarouselControlBuilder visibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        carouselControl.setVisibleOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselControl#setWidth(java.lang.String)
     */
    public CarouselControlBuilder width(java.lang.String v0) {
        carouselControl.setWidth(v0);
        return this;
    }
}
