package biz.freshcode.learn.gwt_bootstrap.client.builder.org.gwtbootstrap3.client.ui;

import org.gwtbootstrap3.client.ui.CarouselIndicators;

/**
 * Generated by DefaultBeanBuilderGenerator
 *
 * @see org.gwtbootstrap3.client.ui.CarouselIndicators
 */
@SuppressWarnings("UnusedDeclaration")
public class CarouselIndicatorsBuilder {
    public final CarouselIndicators carouselIndicators;

    public CarouselIndicatorsBuilder(CarouselIndicators v) {
        carouselIndicators = v;
    }

    public CarouselIndicatorsBuilder() {
        this(new CarouselIndicators());
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#add(com.google.gwt.user.client.ui.Widget)
     */
    public CarouselIndicatorsBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        carouselIndicators.add(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public CarouselIndicatorsBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        carouselIndicators.add(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#addStyleDependentName(java.lang.String)
     */
    public CarouselIndicatorsBuilder addStyleDependentName(java.lang.String v0) {
        carouselIndicators.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#addStyleName(java.lang.String)
     */
    public CarouselIndicatorsBuilder addStyleName(java.lang.String v0) {
        carouselIndicators.addStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setColor(java.lang.String)
     */
    public CarouselIndicatorsBuilder color(java.lang.String v0) {
        carouselIndicators.setColor(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setHeight(java.lang.String)
     */
    public CarouselIndicatorsBuilder height(java.lang.String v0) {
        carouselIndicators.setHeight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setHiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public CarouselIndicatorsBuilder hiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        carouselIndicators.setHiddenOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setId(java.lang.String)
     */
    public CarouselIndicatorsBuilder id(java.lang.String v0) {
        carouselIndicators.setId(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setInline(boolean)
     */
    public CarouselIndicatorsBuilder inline(boolean v0) {
        carouselIndicators.setInline(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setLayoutData(java.lang.Object)
     */
    public CarouselIndicatorsBuilder layoutData(java.lang.Object v0) {
        carouselIndicators.setLayoutData(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setMarginBottom(double)
     */
    public CarouselIndicatorsBuilder marginBottom(double v0) {
        carouselIndicators.setMarginBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setMarginLeft(double)
     */
    public CarouselIndicatorsBuilder marginLeft(double v0) {
        carouselIndicators.setMarginLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setMarginRight(double)
     */
    public CarouselIndicatorsBuilder marginRight(double v0) {
        carouselIndicators.setMarginRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setMarginTop(double)
     */
    public CarouselIndicatorsBuilder marginTop(double v0) {
        carouselIndicators.setMarginTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setPaddingBottom(double)
     */
    public CarouselIndicatorsBuilder paddingBottom(double v0) {
        carouselIndicators.setPaddingBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setPaddingLeft(double)
     */
    public CarouselIndicatorsBuilder paddingLeft(double v0) {
        carouselIndicators.setPaddingLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setPaddingRight(double)
     */
    public CarouselIndicatorsBuilder paddingRight(double v0) {
        carouselIndicators.setPaddingRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setPaddingTop(double)
     */
    public CarouselIndicatorsBuilder paddingTop(double v0) {
        carouselIndicators.setPaddingTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setPixelSize(int, int)
     */
    public CarouselIndicatorsBuilder pixelSize(int v0, int v1) {
        carouselIndicators.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setPull(org.gwtbootstrap3.client.ui.constants.Pull)
     */
    public CarouselIndicatorsBuilder pull(org.gwtbootstrap3.client.ui.constants.Pull v0) {
        carouselIndicators.setPull(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setSize(java.lang.String, java.lang.String)
     */
    public CarouselIndicatorsBuilder size(java.lang.String v0, java.lang.String v1) {
        carouselIndicators.setSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setStyleDependentName(java.lang.String, boolean)
     */
    public CarouselIndicatorsBuilder styleDependentName(java.lang.String v0, boolean v1) {
        carouselIndicators.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setStyleName(java.lang.String)
     */
    public CarouselIndicatorsBuilder styleName(java.lang.String v0) {
        carouselIndicators.setStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setStyleName(java.lang.String, boolean)
     */
    public CarouselIndicatorsBuilder styleName(java.lang.String v0, boolean v1) {
        carouselIndicators.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setStylePrimaryName(java.lang.String)
     */
    public CarouselIndicatorsBuilder stylePrimaryName(java.lang.String v0) {
        carouselIndicators.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setTitle(java.lang.String)
     */
    public CarouselIndicatorsBuilder title(java.lang.String v0) {
        carouselIndicators.setTitle(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setUnstyled(boolean)
     */
    public CarouselIndicatorsBuilder unstyled(boolean v0) {
        carouselIndicators.setUnstyled(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setVisible(boolean)
     */
    public CarouselIndicatorsBuilder visible(boolean v0) {
        carouselIndicators.setVisible(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setVisibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public CarouselIndicatorsBuilder visibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        carouselIndicators.setVisibleOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselIndicators#setWidth(java.lang.String)
     */
    public CarouselIndicatorsBuilder width(java.lang.String v0) {
        carouselIndicators.setWidth(v0);
        return this;
    }
}
