package biz.freshcode.learn.gwt_bootstrap.client.builder.org.gwtbootstrap3.client.ui;

import org.gwtbootstrap3.client.ui.CarouselInner;

/**
 * Generated by BuilderGenerator
 *
 * @see org.gwtbootstrap3.client.ui.CarouselInner
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt_bootstrap.client.builder.BeanBuilder(CarouselInner.class)
public class CarouselInnerBuilder extends biz.freshcode.learn.gwt_bootstrap.client.builder.Construct.Parent<CarouselInnerBuilder> {
    public final CarouselInner carouselInner;

    public CarouselInnerBuilder(CarouselInner v) {
        carouselInner = v;
    }

    public CarouselInnerBuilder() {
        this(new CarouselInner());
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#add(com.google.gwt.user.client.ui.Widget)
     */
    public CarouselInnerBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        carouselInner.add(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public CarouselInnerBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        carouselInner.add(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#addStyleDependentName(java.lang.String)
     */
    public CarouselInnerBuilder addStyleDependentName(java.lang.String v0) {
        carouselInner.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#addStyleName(java.lang.String)
     */
    public CarouselInnerBuilder addStyleName(java.lang.String v0) {
        carouselInner.addStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setColor(java.lang.String)
     */
    public CarouselInnerBuilder color(java.lang.String v0) {
        carouselInner.setColor(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setHeight(java.lang.String)
     */
    public CarouselInnerBuilder height(java.lang.String v0) {
        carouselInner.setHeight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setHiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public CarouselInnerBuilder hiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        carouselInner.setHiddenOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setId(java.lang.String)
     */
    public CarouselInnerBuilder id(java.lang.String v0) {
        carouselInner.setId(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setLayoutData(java.lang.Object)
     */
    public CarouselInnerBuilder layoutData(java.lang.Object v0) {
        carouselInner.setLayoutData(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setMarginBottom(double)
     */
    public CarouselInnerBuilder marginBottom(double v0) {
        carouselInner.setMarginBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setMarginLeft(double)
     */
    public CarouselInnerBuilder marginLeft(double v0) {
        carouselInner.setMarginLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setMarginRight(double)
     */
    public CarouselInnerBuilder marginRight(double v0) {
        carouselInner.setMarginRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setMarginTop(double)
     */
    public CarouselInnerBuilder marginTop(double v0) {
        carouselInner.setMarginTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setPaddingBottom(double)
     */
    public CarouselInnerBuilder paddingBottom(double v0) {
        carouselInner.setPaddingBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setPaddingLeft(double)
     */
    public CarouselInnerBuilder paddingLeft(double v0) {
        carouselInner.setPaddingLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setPaddingRight(double)
     */
    public CarouselInnerBuilder paddingRight(double v0) {
        carouselInner.setPaddingRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setPaddingTop(double)
     */
    public CarouselInnerBuilder paddingTop(double v0) {
        carouselInner.setPaddingTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setPixelSize(int, int)
     */
    public CarouselInnerBuilder pixelSize(int v0, int v1) {
        carouselInner.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setPull(org.gwtbootstrap3.client.ui.constants.Pull)
     */
    public CarouselInnerBuilder pull(org.gwtbootstrap3.client.ui.constants.Pull v0) {
        carouselInner.setPull(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setSize(java.lang.String, java.lang.String)
     */
    public CarouselInnerBuilder size(java.lang.String v0, java.lang.String v1) {
        carouselInner.setSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setStyleDependentName(java.lang.String, boolean)
     */
    public CarouselInnerBuilder styleDependentName(java.lang.String v0, boolean v1) {
        carouselInner.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setStyleName(java.lang.String)
     */
    public CarouselInnerBuilder styleName(java.lang.String v0) {
        carouselInner.setStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setStyleName(java.lang.String, boolean)
     */
    public CarouselInnerBuilder styleName(java.lang.String v0, boolean v1) {
        carouselInner.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setStylePrimaryName(java.lang.String)
     */
    public CarouselInnerBuilder stylePrimaryName(java.lang.String v0) {
        carouselInner.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setTitle(java.lang.String)
     */
    public CarouselInnerBuilder title(java.lang.String v0) {
        carouselInner.setTitle(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setVisible(boolean)
     */
    public CarouselInnerBuilder visible(boolean v0) {
        carouselInner.setVisible(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setVisibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public CarouselInnerBuilder visibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        carouselInner.setVisibleOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.CarouselInner#setWidth(java.lang.String)
     */
    public CarouselInnerBuilder width(java.lang.String v0) {
        carouselInner.setWidth(v0);
        return this;
    }
}
