package biz.freshcode.learn.gwt_bootstrap.client.builder.org.gwtbootstrap3.client.ui;

import org.gwtbootstrap3.client.ui.Heading;

/**
 * Generated by BuilderGenerator
 *
 * @see org.gwtbootstrap3.client.ui.Heading
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt_bootstrap.client.builder.BeanBuilder(Heading.class)
public class HeadingBuilder extends biz.freshcode.learn.gwt_bootstrap.client.builder.Construct.Parent<HeadingBuilder> {
    public final Heading heading;

    public HeadingBuilder(Heading v) {
        heading = v;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#Heading(org.gwtbootstrap3.client.ui.constants.HeadingSize, java.lang.String)
     */
    public HeadingBuilder(org.gwtbootstrap3.client.ui.constants.HeadingSize v0, java.lang.String v1) {
        this(new Heading(v0, v1));
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#Heading(org.gwtbootstrap3.client.ui.constants.HeadingSize)
     */
    public HeadingBuilder(org.gwtbootstrap3.client.ui.constants.HeadingSize v0) {
        this(new Heading(v0));
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#Heading(org.gwtbootstrap3.client.ui.constants.HeadingSize, java.lang.String, java.lang.String)
     */
    public HeadingBuilder(org.gwtbootstrap3.client.ui.constants.HeadingSize v0, java.lang.String v1, java.lang.String v2) {
        this(new Heading(v0, v1, v2));
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#add(com.google.gwt.user.client.ui.Widget)
     */
    public HeadingBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        heading.add(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public HeadingBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        heading.add(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#addStyleDependentName(java.lang.String)
     */
    public HeadingBuilder addStyleDependentName(java.lang.String v0) {
        heading.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#addStyleName(java.lang.String)
     */
    public HeadingBuilder addStyleName(java.lang.String v0) {
        heading.addStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setAlignment(org.gwtbootstrap3.client.ui.constants.Alignment)
     */
    public HeadingBuilder alignment(org.gwtbootstrap3.client.ui.constants.Alignment v0) {
        heading.setAlignment(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setColor(java.lang.String)
     */
    public HeadingBuilder color(java.lang.String v0) {
        heading.setColor(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setEmphasis(org.gwtbootstrap3.client.ui.constants.Emphasis)
     */
    public HeadingBuilder emphasis(org.gwtbootstrap3.client.ui.constants.Emphasis v0) {
        heading.setEmphasis(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setHeight(java.lang.String)
     */
    public HeadingBuilder height(java.lang.String v0) {
        heading.setHeight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setHiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public HeadingBuilder hiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        heading.setHiddenOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setId(java.lang.String)
     */
    public HeadingBuilder id(java.lang.String v0) {
        heading.setId(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setLayoutData(java.lang.Object)
     */
    public HeadingBuilder layoutData(java.lang.Object v0) {
        heading.setLayoutData(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setMarginBottom(double)
     */
    public HeadingBuilder marginBottom(double v0) {
        heading.setMarginBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setMarginLeft(double)
     */
    public HeadingBuilder marginLeft(double v0) {
        heading.setMarginLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setMarginRight(double)
     */
    public HeadingBuilder marginRight(double v0) {
        heading.setMarginRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setMarginTop(double)
     */
    public HeadingBuilder marginTop(double v0) {
        heading.setMarginTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setPaddingBottom(double)
     */
    public HeadingBuilder paddingBottom(double v0) {
        heading.setPaddingBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setPaddingLeft(double)
     */
    public HeadingBuilder paddingLeft(double v0) {
        heading.setPaddingLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setPaddingRight(double)
     */
    public HeadingBuilder paddingRight(double v0) {
        heading.setPaddingRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setPaddingTop(double)
     */
    public HeadingBuilder paddingTop(double v0) {
        heading.setPaddingTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setPixelSize(int, int)
     */
    public HeadingBuilder pixelSize(int v0, int v1) {
        heading.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setPull(org.gwtbootstrap3.client.ui.constants.Pull)
     */
    public HeadingBuilder pull(org.gwtbootstrap3.client.ui.constants.Pull v0) {
        heading.setPull(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setSize(java.lang.String, java.lang.String)
     */
    public HeadingBuilder size(java.lang.String v0, java.lang.String v1) {
        heading.setSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setStyleDependentName(java.lang.String, boolean)
     */
    public HeadingBuilder styleDependentName(java.lang.String v0, boolean v1) {
        heading.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setStyleName(java.lang.String)
     */
    public HeadingBuilder styleName(java.lang.String v0) {
        heading.setStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setStyleName(java.lang.String, boolean)
     */
    public HeadingBuilder styleName(java.lang.String v0, boolean v1) {
        heading.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setStylePrimaryName(java.lang.String)
     */
    public HeadingBuilder stylePrimaryName(java.lang.String v0) {
        heading.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setSubText(java.lang.String)
     */
    public HeadingBuilder subText(java.lang.String v0) {
        heading.setSubText(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setText(java.lang.String)
     */
    public HeadingBuilder text(java.lang.String v0) {
        heading.setText(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setTitle(java.lang.String)
     */
    public HeadingBuilder title(java.lang.String v0) {
        heading.setTitle(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setVisible(boolean)
     */
    public HeadingBuilder visible(boolean v0) {
        heading.setVisible(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setVisibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public HeadingBuilder visibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        heading.setVisibleOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Heading#setWidth(java.lang.String)
     */
    public HeadingBuilder width(java.lang.String v0) {
        heading.setWidth(v0);
        return this;
    }
}
