package biz.freshcode.learn.gwt_bootstrap.client.builder.org.gwtbootstrap3.client.ui;

import org.gwtbootstrap3.client.ui.InlineHelpBlock;

/**
 * Generated by BuilderGenerator
 *
 * @see org.gwtbootstrap3.client.ui.InlineHelpBlock
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt_bootstrap.client.builder.BeanBuilder(InlineHelpBlock.class)
public class InlineHelpBlockBuilder extends biz.freshcode.learn.gwt_bootstrap.client.builder.Construct.Parent<InlineHelpBlockBuilder> {
    public final InlineHelpBlock inlineHelpBlock;

    public InlineHelpBlockBuilder(InlineHelpBlock v) {
        inlineHelpBlock = v;
    }

    public InlineHelpBlockBuilder() {
        this(new InlineHelpBlock());
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#addStyleDependentName(java.lang.String)
     */
    public InlineHelpBlockBuilder addStyleDependentName(java.lang.String v0) {
        inlineHelpBlock.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#addStyleName(java.lang.String)
     */
    public InlineHelpBlockBuilder addStyleName(java.lang.String v0) {
        inlineHelpBlock.addStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setColor(java.lang.String)
     */
    public InlineHelpBlockBuilder color(java.lang.String v0) {
        inlineHelpBlock.setColor(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setError(java.lang.String)
     */
    public InlineHelpBlockBuilder error(java.lang.String v0) {
        inlineHelpBlock.setError(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setHTML(java.lang.String)
     */
    public InlineHelpBlockBuilder hTML(java.lang.String v0) {
        inlineHelpBlock.setHTML(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setHeight(java.lang.String)
     */
    public InlineHelpBlockBuilder height(java.lang.String v0) {
        inlineHelpBlock.setHeight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setHiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public InlineHelpBlockBuilder hiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        inlineHelpBlock.setHiddenOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setIconType(org.gwtbootstrap3.client.ui.constants.IconType)
     */
    public InlineHelpBlockBuilder iconType(org.gwtbootstrap3.client.ui.constants.IconType v0) {
        inlineHelpBlock.setIconType(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setId(java.lang.String)
     */
    public InlineHelpBlockBuilder id(java.lang.String v0) {
        inlineHelpBlock.setId(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setLayoutData(java.lang.Object)
     */
    public InlineHelpBlockBuilder layoutData(java.lang.Object v0) {
        inlineHelpBlock.setLayoutData(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setMarginBottom(double)
     */
    public InlineHelpBlockBuilder marginBottom(double v0) {
        inlineHelpBlock.setMarginBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setMarginLeft(double)
     */
    public InlineHelpBlockBuilder marginLeft(double v0) {
        inlineHelpBlock.setMarginLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setMarginRight(double)
     */
    public InlineHelpBlockBuilder marginRight(double v0) {
        inlineHelpBlock.setMarginRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setMarginTop(double)
     */
    public InlineHelpBlockBuilder marginTop(double v0) {
        inlineHelpBlock.setMarginTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setPaddingBottom(double)
     */
    public InlineHelpBlockBuilder paddingBottom(double v0) {
        inlineHelpBlock.setPaddingBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setPaddingLeft(double)
     */
    public InlineHelpBlockBuilder paddingLeft(double v0) {
        inlineHelpBlock.setPaddingLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setPaddingRight(double)
     */
    public InlineHelpBlockBuilder paddingRight(double v0) {
        inlineHelpBlock.setPaddingRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setPaddingTop(double)
     */
    public InlineHelpBlockBuilder paddingTop(double v0) {
        inlineHelpBlock.setPaddingTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setPixelSize(int, int)
     */
    public InlineHelpBlockBuilder pixelSize(int v0, int v1) {
        inlineHelpBlock.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setPull(org.gwtbootstrap3.client.ui.constants.Pull)
     */
    public InlineHelpBlockBuilder pull(org.gwtbootstrap3.client.ui.constants.Pull v0) {
        inlineHelpBlock.setPull(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setSize(java.lang.String, java.lang.String)
     */
    public InlineHelpBlockBuilder size(java.lang.String v0, java.lang.String v1) {
        inlineHelpBlock.setSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setStyleDependentName(java.lang.String, boolean)
     */
    public InlineHelpBlockBuilder styleDependentName(java.lang.String v0, boolean v1) {
        inlineHelpBlock.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setStyleName(java.lang.String)
     */
    public InlineHelpBlockBuilder styleName(java.lang.String v0) {
        inlineHelpBlock.setStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setStyleName(java.lang.String, boolean)
     */
    public InlineHelpBlockBuilder styleName(java.lang.String v0, boolean v1) {
        inlineHelpBlock.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setStylePrimaryName(java.lang.String)
     */
    public InlineHelpBlockBuilder stylePrimaryName(java.lang.String v0) {
        inlineHelpBlock.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setText(java.lang.String)
     */
    public InlineHelpBlockBuilder text(java.lang.String v0) {
        inlineHelpBlock.setText(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setTitle(java.lang.String)
     */
    public InlineHelpBlockBuilder title(java.lang.String v0) {
        inlineHelpBlock.setTitle(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setVisible(boolean)
     */
    public InlineHelpBlockBuilder visible(boolean v0) {
        inlineHelpBlock.setVisible(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setVisibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public InlineHelpBlockBuilder visibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        inlineHelpBlock.setVisibleOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.InlineHelpBlock#setWidth(java.lang.String)
     */
    public InlineHelpBlockBuilder width(java.lang.String v0) {
        inlineHelpBlock.setWidth(v0);
        return this;
    }
}
