package biz.freshcode.learn.gwt_bootstrap.client.builder.org.gwtbootstrap3.client.ui;

import org.gwtbootstrap3.client.ui.Jumbotron;

/**
 * Generated by BuilderGenerator
 *
 * @see org.gwtbootstrap3.client.ui.Jumbotron
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt_bootstrap.client.builder.BeanBuilder(Jumbotron.class)
public class JumbotronBuilder extends biz.freshcode.learn.gwt_bootstrap.client.builder.Construct.Parent<JumbotronBuilder> {
    public final Jumbotron jumbotron;

    public JumbotronBuilder(Jumbotron v) {
        jumbotron = v;
    }

    public JumbotronBuilder() {
        this(new Jumbotron());
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#add(com.google.gwt.user.client.ui.Widget)
     */
    public JumbotronBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        jumbotron.add(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public JumbotronBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        jumbotron.add(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#addStyleDependentName(java.lang.String)
     */
    public JumbotronBuilder addStyleDependentName(java.lang.String v0) {
        jumbotron.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#addStyleName(java.lang.String)
     */
    public JumbotronBuilder addStyleName(java.lang.String v0) {
        jumbotron.addStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setColor(java.lang.String)
     */
    public JumbotronBuilder color(java.lang.String v0) {
        jumbotron.setColor(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setHeight(java.lang.String)
     */
    public JumbotronBuilder height(java.lang.String v0) {
        jumbotron.setHeight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setHiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public JumbotronBuilder hiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        jumbotron.setHiddenOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setId(java.lang.String)
     */
    public JumbotronBuilder id(java.lang.String v0) {
        jumbotron.setId(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setLayoutData(java.lang.Object)
     */
    public JumbotronBuilder layoutData(java.lang.Object v0) {
        jumbotron.setLayoutData(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setMarginBottom(double)
     */
    public JumbotronBuilder marginBottom(double v0) {
        jumbotron.setMarginBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setMarginLeft(double)
     */
    public JumbotronBuilder marginLeft(double v0) {
        jumbotron.setMarginLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setMarginRight(double)
     */
    public JumbotronBuilder marginRight(double v0) {
        jumbotron.setMarginRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setMarginTop(double)
     */
    public JumbotronBuilder marginTop(double v0) {
        jumbotron.setMarginTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setPaddingBottom(double)
     */
    public JumbotronBuilder paddingBottom(double v0) {
        jumbotron.setPaddingBottom(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setPaddingLeft(double)
     */
    public JumbotronBuilder paddingLeft(double v0) {
        jumbotron.setPaddingLeft(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setPaddingRight(double)
     */
    public JumbotronBuilder paddingRight(double v0) {
        jumbotron.setPaddingRight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setPaddingTop(double)
     */
    public JumbotronBuilder paddingTop(double v0) {
        jumbotron.setPaddingTop(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setPixelSize(int, int)
     */
    public JumbotronBuilder pixelSize(int v0, int v1) {
        jumbotron.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setPull(org.gwtbootstrap3.client.ui.constants.Pull)
     */
    public JumbotronBuilder pull(org.gwtbootstrap3.client.ui.constants.Pull v0) {
        jumbotron.setPull(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setSize(java.lang.String, java.lang.String)
     */
    public JumbotronBuilder size(java.lang.String v0, java.lang.String v1) {
        jumbotron.setSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setStyleDependentName(java.lang.String, boolean)
     */
    public JumbotronBuilder styleDependentName(java.lang.String v0, boolean v1) {
        jumbotron.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setStyleName(java.lang.String)
     */
    public JumbotronBuilder styleName(java.lang.String v0) {
        jumbotron.setStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setStyleName(java.lang.String, boolean)
     */
    public JumbotronBuilder styleName(java.lang.String v0, boolean v1) {
        jumbotron.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setStylePrimaryName(java.lang.String)
     */
    public JumbotronBuilder stylePrimaryName(java.lang.String v0) {
        jumbotron.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setTitle(java.lang.String)
     */
    public JumbotronBuilder title(java.lang.String v0) {
        jumbotron.setTitle(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setVisible(boolean)
     */
    public JumbotronBuilder visible(boolean v0) {
        jumbotron.setVisible(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setVisibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public JumbotronBuilder visibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        jumbotron.setVisibleOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.Jumbotron#setWidth(java.lang.String)
     */
    public JumbotronBuilder width(java.lang.String v0) {
        jumbotron.setWidth(v0);
        return this;
    }
}
