package biz.freshcode.learn.gwt_bootstrap.client.builder.org.gwtbootstrap3.client.ui;

import org.gwtbootstrap3.client.ui.NavbarCollapseButton;

/**
 * Generated by DefaultBeanBuilderGenerator
 *
 * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton
 */
@SuppressWarnings("UnusedDeclaration")
public class NavbarCollapseButtonBuilder {
    public final NavbarCollapseButton navbarCollapseButton;

    public NavbarCollapseButtonBuilder(NavbarCollapseButton v) {
        navbarCollapseButton = v;
    }

    public NavbarCollapseButtonBuilder() {
        this(new NavbarCollapseButton());
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#addStyleDependentName(java.lang.String)
     */
    public NavbarCollapseButtonBuilder addStyleDependentName(java.lang.String v0) {
        navbarCollapseButton.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#addStyleName(java.lang.String)
     */
    public NavbarCollapseButtonBuilder addStyleName(java.lang.String v0) {
        navbarCollapseButton.addStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setDataTarget(java.lang.String)
     */
    public NavbarCollapseButtonBuilder dataTarget(java.lang.String v0) {
        navbarCollapseButton.setDataTarget(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setDataTargetWidget(com.google.gwt.user.client.ui.Widget)
     */
    public NavbarCollapseButtonBuilder dataTargetWidget(com.google.gwt.user.client.ui.Widget v0) {
        navbarCollapseButton.setDataTargetWidget(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setDataTargetWidgets(java.util.List)
     */
    public NavbarCollapseButtonBuilder dataTargetWidgets(java.util.List<com.google.gwt.user.client.ui.Widget> v0) {
        navbarCollapseButton.setDataTargetWidgets(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setHeight(java.lang.String)
     */
    public NavbarCollapseButtonBuilder height(java.lang.String v0) {
        navbarCollapseButton.setHeight(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setHiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public NavbarCollapseButtonBuilder hiddenOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        navbarCollapseButton.setHiddenOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setLayoutData(java.lang.Object)
     */
    public NavbarCollapseButtonBuilder layoutData(java.lang.Object v0) {
        navbarCollapseButton.setLayoutData(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setPixelSize(int, int)
     */
    public NavbarCollapseButtonBuilder pixelSize(int v0, int v1) {
        navbarCollapseButton.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setPull(org.gwtbootstrap3.client.ui.constants.Pull)
     */
    public NavbarCollapseButtonBuilder pull(org.gwtbootstrap3.client.ui.constants.Pull v0) {
        navbarCollapseButton.setPull(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setSize(java.lang.String, java.lang.String)
     */
    public NavbarCollapseButtonBuilder size(java.lang.String v0, java.lang.String v1) {
        navbarCollapseButton.setSize(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setStyleDependentName(java.lang.String, boolean)
     */
    public NavbarCollapseButtonBuilder styleDependentName(java.lang.String v0, boolean v1) {
        navbarCollapseButton.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setStyleName(java.lang.String)
     */
    public NavbarCollapseButtonBuilder styleName(java.lang.String v0) {
        navbarCollapseButton.setStyleName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setStyleName(java.lang.String, boolean)
     */
    public NavbarCollapseButtonBuilder styleName(java.lang.String v0, boolean v1) {
        navbarCollapseButton.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setStylePrimaryName(java.lang.String)
     */
    public NavbarCollapseButtonBuilder stylePrimaryName(java.lang.String v0) {
        navbarCollapseButton.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setTitle(java.lang.String)
     */
    public NavbarCollapseButtonBuilder title(java.lang.String v0) {
        navbarCollapseButton.setTitle(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setVisible(boolean)
     */
    public NavbarCollapseButtonBuilder visible(boolean v0) {
        navbarCollapseButton.setVisible(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setVisibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize)
     */
    public NavbarCollapseButtonBuilder visibleOn(org.gwtbootstrap3.client.ui.constants.DeviceSize v0) {
        navbarCollapseButton.setVisibleOn(v0);
        return this;
    }

    /**
     * @see org.gwtbootstrap3.client.ui.NavbarCollapseButton#setWidth(java.lang.String)
     */
    public NavbarCollapseButtonBuilder width(java.lang.String v0) {
        navbarCollapseButton.setWidth(v0);
        return this;
    }
}
