package biz.freshcode.learn.gwt.common.client.builder.gwt;

import com.google.gwt.user.client.ui.HTMLPanel;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.google.gwt.user.client.ui.HTMLPanel
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt.common.client.builder.BeanBuilder(HTMLPanel.class)
public class HTMLPanelBuilder extends biz.freshcode.learn.gwt.common.client.builder.Construct.Parent<HTMLPanelBuilder> {
    public final HTMLPanel hTMLPanel;

    public HTMLPanelBuilder(HTMLPanel v) {
        hTMLPanel = v;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#HTMLPanel(java.lang.String, java.lang.String)
     */
    public HTMLPanelBuilder(java.lang.String v0, java.lang.String v1) {
        this(new HTMLPanel(v0, v1));
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#HTMLPanel(com.google.gwt.safehtml.shared.SafeHtml)
     */
    public HTMLPanelBuilder(com.google.gwt.safehtml.shared.SafeHtml v0) {
        this(new HTMLPanel(v0));
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#HTMLPanel(java.lang.String)
     */
    public HTMLPanelBuilder(java.lang.String v0) {
        this(new HTMLPanel(v0));
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#add(com.google.gwt.user.client.ui.Widget)
     */
    public HTMLPanelBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        hTMLPanel.add(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public HTMLPanelBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        hTMLPanel.add(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#add(com.google.gwt.user.client.ui.Widget, com.google.gwt.dom.client.Element)
     */
    public HTMLPanelBuilder add(com.google.gwt.user.client.ui.Widget v0, com.google.gwt.dom.client.Element v1) {
        hTMLPanel.add(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#add(com.google.gwt.user.client.ui.Widget, java.lang.String)
     */
    public HTMLPanelBuilder add(com.google.gwt.user.client.ui.Widget v0, java.lang.String v1) {
        hTMLPanel.add(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#addAndReplaceElement(com.google.gwt.user.client.ui.Widget, com.google.gwt.dom.client.Element)
     */
    public HTMLPanelBuilder addAndReplaceElement(com.google.gwt.user.client.ui.Widget v0, com.google.gwt.dom.client.Element v1) {
        hTMLPanel.addAndReplaceElement(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#addAndReplaceElement(com.google.gwt.user.client.ui.Widget, com.google.gwt.user.client.Element)
     */
    @SuppressWarnings("deprecation")
    @Deprecated
    public HTMLPanelBuilder addAndReplaceElement(com.google.gwt.user.client.ui.Widget v0, com.google.gwt.user.client.Element v1) {
        hTMLPanel.addAndReplaceElement(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#addAndReplaceElement(com.google.gwt.user.client.ui.Widget, java.lang.String)
     */
    public HTMLPanelBuilder addAndReplaceElement(com.google.gwt.user.client.ui.Widget v0, java.lang.String v1) {
        hTMLPanel.addAndReplaceElement(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#addAndReplaceElement(com.google.gwt.user.client.ui.IsWidget, com.google.gwt.dom.client.Element)
     */
    public HTMLPanelBuilder addAndReplaceElement(com.google.gwt.user.client.ui.IsWidget v0, com.google.gwt.dom.client.Element v1) {
        hTMLPanel.addAndReplaceElement(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#addAndReplaceElement(com.google.gwt.user.client.ui.IsWidget, com.google.gwt.user.client.Element)
     */
    @SuppressWarnings("deprecation")
    @Deprecated
    public HTMLPanelBuilder addAndReplaceElement(com.google.gwt.user.client.ui.IsWidget v0, com.google.gwt.user.client.Element v1) {
        hTMLPanel.addAndReplaceElement(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#addAndReplaceElement(com.google.gwt.user.client.ui.IsWidget, java.lang.String)
     */
    public HTMLPanelBuilder addAndReplaceElement(com.google.gwt.user.client.ui.IsWidget v0, java.lang.String v1) {
        hTMLPanel.addAndReplaceElement(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#addStyleDependentName(java.lang.String)
     */
    public HTMLPanelBuilder addStyleDependentName(java.lang.String v0) {
        hTMLPanel.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#addStyleName(java.lang.String)
     */
    public HTMLPanelBuilder addStyleName(java.lang.String v0) {
        hTMLPanel.addStyleName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#setHeight(java.lang.String)
     */
    public HTMLPanelBuilder height(java.lang.String v0) {
        hTMLPanel.setHeight(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#setLayoutData(java.lang.Object)
     */
    public HTMLPanelBuilder layoutData(java.lang.Object v0) {
        hTMLPanel.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#setPixelSize(int, int)
     */
    public HTMLPanelBuilder pixelSize(int v0, int v1) {
        hTMLPanel.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#setSize(java.lang.String, java.lang.String)
     */
    public HTMLPanelBuilder size(java.lang.String v0, java.lang.String v1) {
        hTMLPanel.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#setStyleDependentName(java.lang.String, boolean)
     */
    public HTMLPanelBuilder styleDependentName(java.lang.String v0, boolean v1) {
        hTMLPanel.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#setStyleName(java.lang.String)
     */
    public HTMLPanelBuilder styleName(java.lang.String v0) {
        hTMLPanel.setStyleName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#setStyleName(java.lang.String, boolean)
     */
    public HTMLPanelBuilder styleName(java.lang.String v0, boolean v1) {
        hTMLPanel.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#setStylePrimaryName(java.lang.String)
     */
    public HTMLPanelBuilder stylePrimaryName(java.lang.String v0) {
        hTMLPanel.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#setTitle(java.lang.String)
     */
    public HTMLPanelBuilder title(java.lang.String v0) {
        hTMLPanel.setTitle(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#setVisible(boolean)
     */
    public HTMLPanelBuilder visible(boolean v0) {
        hTMLPanel.setVisible(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HTMLPanel#setWidth(java.lang.String)
     */
    public HTMLPanelBuilder width(java.lang.String v0) {
        hTMLPanel.setWidth(v0);
        return this;
    }
}
