package biz.freshcode.learn.gwt2.common.client.builder.gxt.form;

import com.sencha.gxt.widget.core.client.form.FormPanel;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.widget.core.client.form.FormPanel
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt2.common.client.builder.BeanBuilder(FormPanel.class)
public class FormPanelBuilder extends biz.freshcode.learn.gwt2.common.client.builder.Construct.Parent<FormPanelBuilder> {
    public final FormPanel formPanel;

    public FormPanelBuilder(FormPanel v) {
        formPanel = v;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#FormPanel()
     */
    public FormPanelBuilder() {
        this(new FormPanel());
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#add(com.google.gwt.user.client.ui.Widget)
     */
    public FormPanelBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        formPanel.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public FormPanelBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        formPanel.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#add(com.google.gwt.user.client.ui.Widget, com.sencha.gxt.widget.core.client.container.MarginData)
     */
    public FormPanelBuilder add(com.google.gwt.user.client.ui.Widget v0, com.sencha.gxt.widget.core.client.container.MarginData v1) {
        formPanel.add(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#add(com.google.gwt.user.client.ui.IsWidget, com.sencha.gxt.widget.core.client.container.MarginData)
     */
    public FormPanelBuilder add(com.google.gwt.user.client.ui.IsWidget v0, com.sencha.gxt.widget.core.client.container.MarginData v1) {
        formPanel.add(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#addGestureRecognizer(com.sencha.gxt.core.client.gestures.GestureRecognizer)
     */
    public FormPanelBuilder addGestureRecognizer(com.sencha.gxt.core.client.gestures.GestureRecognizer v0) {
        formPanel.addGestureRecognizer(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#addStyleDependentName(java.lang.String)
     */
    public FormPanelBuilder addStyleDependentName(java.lang.String v0) {
        formPanel.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#addStyleName(java.lang.String)
     */
    public FormPanelBuilder addStyleName(java.lang.String v0) {
        formPanel.addStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#addStyleOnOver(com.google.gwt.dom.client.Element, java.lang.String)
     */
    public FormPanelBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        formPanel.addStyleOnOver(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setAction(java.lang.String)
     */
    public FormPanelBuilder action(java.lang.String v0) {
        formPanel.setAction(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setAction(com.google.gwt.safehtml.shared.SafeUri)
     */
    public FormPanelBuilder action(com.google.gwt.safehtml.shared.SafeUri v0) {
        formPanel.setAction(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setAdjustSize(boolean)
     */
    public FormPanelBuilder adjustSize(boolean v0) {
        formPanel.setAdjustSize(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setAllowTextSelection(boolean)
     */
    public FormPanelBuilder allowTextSelection(boolean v0) {
        formPanel.setAllowTextSelection(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setBorders(boolean)
     */
    public FormPanelBuilder borders(boolean v0) {
        formPanel.setBorders(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setBounds(com.sencha.gxt.core.client.util.Rectangle)
     */
    public FormPanelBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        formPanel.setBounds(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setBounds(int, int, int, int)
     */
    public FormPanelBuilder bounds(int v0, int v1, int v2, int v3) {
        formPanel.setBounds(v0, v1, v2, v3);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setContextMenu(com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public FormPanelBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        formPanel.setContextMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setData(java.lang.String, java.lang.Object)
     */
    public FormPanelBuilder data(java.lang.String v0, java.lang.Object v1) {
        formPanel.setData(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setDeferHeight(boolean)
     */
    public FormPanelBuilder deferHeight(boolean v0) {
        formPanel.setDeferHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setEnabled(boolean)
     */
    public FormPanelBuilder enabled(boolean v0) {
        formPanel.setEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setEncoding(com.sencha.gxt.widget.core.client.form.FormPanel.Encoding)
     */
    public FormPanelBuilder encoding(com.sencha.gxt.widget.core.client.form.FormPanel.Encoding v0) {
        formPanel.setEncoding(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setHeight(java.lang.String)
     */
    public FormPanelBuilder height(java.lang.String v0) {
        formPanel.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setHeight(int)
     */
    public FormPanelBuilder height(int v0) {
        formPanel.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setHideMode(com.sencha.gxt.core.client.Style.HideMode)
     */
    public FormPanelBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        formPanel.setHideMode(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setId(java.lang.String)
     */
    public FormPanelBuilder id(java.lang.String v0) {
        formPanel.setId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setItemId(java.lang.String)
     */
    public FormPanelBuilder itemId(java.lang.String v0) {
        formPanel.setItemId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setLabelAlign(com.sencha.gxt.widget.core.client.form.FormPanel.LabelAlign)
     */
    public FormPanelBuilder labelAlign(com.sencha.gxt.widget.core.client.form.FormPanel.LabelAlign v0) {
        formPanel.setLabelAlign(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setLabelWidth(int)
     */
    public FormPanelBuilder labelWidth(int v0) {
        formPanel.setLabelWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setLayoutData(java.lang.Object)
     */
    public FormPanelBuilder layoutData(java.lang.Object v0) {
        formPanel.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setMethod(com.sencha.gxt.widget.core.client.form.FormPanel.Method)
     */
    public FormPanelBuilder method(com.sencha.gxt.widget.core.client.form.FormPanel.Method v0) {
        formPanel.setMethod(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setPagePosition(int, int)
     */
    public FormPanelBuilder pagePosition(int v0, int v1) {
        formPanel.setPagePosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setPixelSize(int, int)
     */
    public FormPanelBuilder pixelSize(int v0, int v1) {
        formPanel.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setPosition(int, int)
     */
    public FormPanelBuilder position(int v0, int v1) {
        formPanel.setPosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setResize(boolean)
     */
    public FormPanelBuilder resize(boolean v0) {
        formPanel.setResize(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setShadow(boolean)
     */
    public FormPanelBuilder shadow(boolean v0) {
        formPanel.setShadow(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setShadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition)
     */
    public FormPanelBuilder shadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition v0) {
        formPanel.setShadowPosition(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setSize(java.lang.String, java.lang.String)
     */
    public FormPanelBuilder size(java.lang.String v0, java.lang.String v1) {
        formPanel.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setStateId(java.lang.String)
     */
    public FormPanelBuilder stateId(java.lang.String v0) {
        formPanel.setStateId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setStateful(boolean)
     */
    public FormPanelBuilder stateful(boolean v0) {
        formPanel.setStateful(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setStyleDependentName(java.lang.String, boolean)
     */
    public FormPanelBuilder styleDependentName(java.lang.String v0, boolean v1) {
        formPanel.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setStyleName(java.lang.String)
     */
    public FormPanelBuilder styleName(java.lang.String v0) {
        formPanel.setStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setStyleName(java.lang.String, boolean)
     */
    public FormPanelBuilder styleName(java.lang.String v0, boolean v1) {
        formPanel.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setStylePrimaryName(java.lang.String)
     */
    public FormPanelBuilder stylePrimaryName(java.lang.String v0) {
        formPanel.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setTabIndex(int)
     */
    public FormPanelBuilder tabIndex(int v0) {
        formPanel.setTabIndex(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setTitle(java.lang.String)
     */
    public FormPanelBuilder title(java.lang.String v0) {
        formPanel.setTitle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setToolTip(java.lang.String)
     */
    public FormPanelBuilder toolTip(java.lang.String v0) {
        formPanel.setToolTip(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setToolTip(com.google.gwt.safehtml.shared.SafeHtml)
     */
    public FormPanelBuilder toolTip(com.google.gwt.safehtml.shared.SafeHtml v0) {
        formPanel.setToolTip(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setToolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig)
     */
    public FormPanelBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        formPanel.setToolTipConfig(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setVisible(boolean)
     */
    public FormPanelBuilder visible(boolean v0) {
        formPanel.setVisible(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setWidget(com.google.gwt.user.client.ui.Widget)
     */
    public FormPanelBuilder widget(com.google.gwt.user.client.ui.Widget v0) {
        formPanel.setWidget(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setWidget(com.google.gwt.user.client.ui.IsWidget)
     */
    public FormPanelBuilder widget(com.google.gwt.user.client.ui.IsWidget v0) {
        formPanel.setWidget(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setWidth(java.lang.String)
     */
    public FormPanelBuilder width(java.lang.String v0) {
        formPanel.setWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.FormPanel#setWidth(int)
     */
    public FormPanelBuilder width(int v0) {
        formPanel.setWidth(v0);
        return this;
    }
}
