package biz.freshcode.learn.gwt2.common.client.builder.gxt.form;

import com.sencha.gxt.widget.core.client.form.Radio;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.widget.core.client.form.Radio
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt2.common.client.builder.BeanBuilder(Radio.class)
public class RadioBuilder extends biz.freshcode.learn.gwt2.common.client.builder.Construct.Parent<RadioBuilder> {
    public final Radio radio;

    public RadioBuilder(Radio v) {
        radio = v;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#Radio()
     */
    public RadioBuilder() {
        this(new Radio());
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#Radio(com.sencha.gxt.cell.core.client.form.RadioCell)
     */
    public RadioBuilder(com.sencha.gxt.cell.core.client.form.RadioCell v0) {
        this(new Radio(v0));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#addStyleDependentName(java.lang.String)
     */
    public RadioBuilder addStyleDependentName(java.lang.String v0) {
        radio.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#addStyleName(java.lang.String)
     */
    public RadioBuilder addStyleName(java.lang.String v0) {
        radio.addStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#addStyleOnOver(com.google.gwt.dom.client.Element, java.lang.String)
     */
    public RadioBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        radio.addStyleOnOver(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#addValidator(com.sencha.gxt.widget.core.client.form.Validator)
     */
    public RadioBuilder addValidator(com.sencha.gxt.widget.core.client.form.Validator<Boolean> v0) {
        radio.addValidator(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setAllowTextSelection(boolean)
     */
    public RadioBuilder allowTextSelection(boolean v0) {
        radio.setAllowTextSelection(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setAutoValidate(boolean)
     */
    public RadioBuilder autoValidate(boolean v0) {
        radio.setAutoValidate(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setBorders(boolean)
     */
    public RadioBuilder borders(boolean v0) {
        radio.setBorders(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setBounds(com.sencha.gxt.core.client.util.Rectangle)
     */
    public RadioBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        radio.setBounds(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setBounds(int, int, int, int)
     */
    public RadioBuilder bounds(int v0, int v1, int v2, int v3) {
        radio.setBounds(v0, v1, v2, v3);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setBoxLabel(java.lang.String)
     */
    public RadioBuilder boxLabel(java.lang.String v0) {
        radio.setBoxLabel(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setContextMenu(com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public RadioBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        radio.setContextMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setData(java.lang.String, java.lang.Object)
     */
    public RadioBuilder data(java.lang.String v0, java.lang.Object v1) {
        radio.setData(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setDeferHeight(boolean)
     */
    public RadioBuilder deferHeight(boolean v0) {
        radio.setDeferHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setDelegate(com.google.gwt.editor.client.EditorDelegate)
     */
    public RadioBuilder delegate(com.google.gwt.editor.client.EditorDelegate<Boolean> v0) {
        radio.setDelegate(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setEnabled(boolean)
     */
    public RadioBuilder enabled(boolean v0) {
        radio.setEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setErrorSupport(com.sencha.gxt.widget.core.client.form.error.ErrorHandler)
     */
    public RadioBuilder errorSupport(com.sencha.gxt.widget.core.client.form.error.ErrorHandler v0) {
        radio.setErrorSupport(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setHeight(java.lang.String)
     */
    public RadioBuilder height(java.lang.String v0) {
        radio.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setHeight(int)
     */
    public RadioBuilder height(int v0) {
        radio.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setHideMode(com.sencha.gxt.core.client.Style.HideMode)
     */
    public RadioBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        radio.setHideMode(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setId(java.lang.String)
     */
    public RadioBuilder id(java.lang.String v0) {
        radio.setId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setItemId(java.lang.String)
     */
    public RadioBuilder itemId(java.lang.String v0) {
        radio.setItemId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setLayoutData(java.lang.Object)
     */
    public RadioBuilder layoutData(java.lang.Object v0) {
        radio.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setName(java.lang.String)
     */
    public RadioBuilder name(java.lang.String v0) {
        radio.setName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setOriginalValue(Object)
     */
    public RadioBuilder originalValue(Boolean v0) {
        radio.setOriginalValue(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setPagePosition(int, int)
     */
    public RadioBuilder pagePosition(int v0, int v1) {
        radio.setPagePosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setPixelSize(int, int)
     */
    public RadioBuilder pixelSize(int v0, int v1) {
        radio.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setPosition(int, int)
     */
    public RadioBuilder position(int v0, int v1) {
        radio.setPosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setReadOnly(boolean)
     */
    public RadioBuilder readOnly(boolean v0) {
        radio.setReadOnly(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setShadow(boolean)
     */
    public RadioBuilder shadow(boolean v0) {
        radio.setShadow(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setShadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition)
     */
    public RadioBuilder shadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition v0) {
        radio.setShadowPosition(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setSize(java.lang.String, java.lang.String)
     */
    public RadioBuilder size(java.lang.String v0, java.lang.String v1) {
        radio.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setStateId(java.lang.String)
     */
    public RadioBuilder stateId(java.lang.String v0) {
        radio.setStateId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setStateful(boolean)
     */
    public RadioBuilder stateful(boolean v0) {
        radio.setStateful(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setStyleDependentName(java.lang.String, boolean)
     */
    public RadioBuilder styleDependentName(java.lang.String v0, boolean v1) {
        radio.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setStyleName(java.lang.String)
     */
    public RadioBuilder styleName(java.lang.String v0) {
        radio.setStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setStyleName(java.lang.String, boolean)
     */
    public RadioBuilder styleName(java.lang.String v0, boolean v1) {
        radio.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setStylePrimaryName(java.lang.String)
     */
    public RadioBuilder stylePrimaryName(java.lang.String v0) {
        radio.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setTabIndex(int)
     */
    public RadioBuilder tabIndex(int v0) {
        radio.setTabIndex(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setTitle(java.lang.String)
     */
    public RadioBuilder title(java.lang.String v0) {
        radio.setTitle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setToolTip(java.lang.String)
     */
    public RadioBuilder toolTip(java.lang.String v0) {
        radio.setToolTip(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setToolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig)
     */
    public RadioBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        radio.setToolTipConfig(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setValidateOnBlur(boolean)
     */
    public RadioBuilder validateOnBlur(boolean v0) {
        radio.setValidateOnBlur(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setValidationDelay(int)
     */
    public RadioBuilder validationDelay(int v0) {
        radio.setValidationDelay(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setValue(java.lang.Boolean)
     */
    public RadioBuilder value(java.lang.Boolean v0) {
        radio.setValue(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setValue(Object, boolean)
     */
    public RadioBuilder value(Boolean v0, boolean v1) {
        radio.setValue(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setValue(Object, boolean, boolean)
     */
    public RadioBuilder value(Boolean v0, boolean v1, boolean v2) {
        radio.setValue(v0, v1, v2);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setVisible(boolean)
     */
    public RadioBuilder visible(boolean v0) {
        radio.setVisible(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setWidth(java.lang.String)
     */
    public RadioBuilder width(java.lang.String v0) {
        radio.setWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.form.Radio#setWidth(int)
     */
    public RadioBuilder width(int v0) {
        radio.setWidth(v0);
        return this;
    }
}
