package biz.freshcode.learn.gwt.client.builder.gxt;

import com.sencha.gxt.widget.core.client.Popup;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.widget.core.client.Popup
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt.client.builder.BeanBuilder(Popup.class)
public class PopupBuilder extends biz.freshcode.learn.gwt.client.builder.Construct.Parent<PopupBuilder> {
    public final Popup popup;

    public PopupBuilder(Popup v) {
        popup = v;
    }

    public PopupBuilder() {
        this(new Popup());
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#add(com.google.gwt.user.client.ui.Widget)
     */
    public PopupBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        popup.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public PopupBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        popup.add(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#add(com.google.gwt.user.client.ui.Widget, com.sencha.gxt.widget.core.client.container.MarginData)
     */
    public PopupBuilder add(com.google.gwt.user.client.ui.Widget v0, com.sencha.gxt.widget.core.client.container.MarginData v1) {
        popup.add(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#addStyleDependentName(java.lang.String)
     */
    public PopupBuilder addStyleDependentName(java.lang.String v0) {
        popup.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#addStyleName(java.lang.String)
     */
    public PopupBuilder addStyleName(java.lang.String v0) {
        popup.addStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#addStyleOnOver(com.google.gwt.dom.client.Element, java.lang.String)
     */
    public PopupBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        popup.addStyleOnOver(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setAllowTextSelection(boolean)
     */
    public PopupBuilder allowTextSelection(boolean v0) {
        popup.setAllowTextSelection(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setAnimate(boolean)
     */
    public PopupBuilder animate(boolean v0) {
        popup.setAnimate(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setAutoFocus(boolean)
     */
    public PopupBuilder autoFocus(boolean v0) {
        popup.setAutoFocus(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setAutoHide(boolean)
     */
    public PopupBuilder autoHide(boolean v0) {
        popup.setAutoHide(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setBorders(boolean)
     */
    public PopupBuilder borders(boolean v0) {
        popup.setBorders(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setBounds(com.sencha.gxt.core.client.util.Rectangle)
     */
    public PopupBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        popup.setBounds(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setBounds(int, int, int, int)
     */
    public PopupBuilder bounds(int v0, int v1, int v2, int v3) {
        popup.setBounds(v0, v1, v2, v3);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setConstrainViewport(boolean)
     */
    public PopupBuilder constrainViewport(boolean v0) {
        popup.setConstrainViewport(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setContextMenu(com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public PopupBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        popup.setContextMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setData(java.lang.String, java.lang.Object)
     */
    public PopupBuilder data(java.lang.String v0, java.lang.Object v1) {
        popup.setData(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setDefaultAlign(com.sencha.gxt.core.client.Style.AnchorAlignment)
     */
    public PopupBuilder defaultAlign(com.sencha.gxt.core.client.Style.AnchorAlignment v0) {
        popup.setDefaultAlign(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setDeferHeight(boolean)
     */
    public PopupBuilder deferHeight(boolean v0) {
        popup.setDeferHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setEnabled(boolean)
     */
    public PopupBuilder enabled(boolean v0) {
        popup.setEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setHeight(int)
     */
    public PopupBuilder height(int v0) {
        popup.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setHeight(java.lang.String)
     */
    public PopupBuilder height(java.lang.String v0) {
        popup.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setHideMode(com.sencha.gxt.core.client.Style.HideMode)
     */
    public PopupBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        popup.setHideMode(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setId(java.lang.String)
     */
    public PopupBuilder id(java.lang.String v0) {
        popup.setId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setItemId(java.lang.String)
     */
    public PopupBuilder itemId(java.lang.String v0) {
        popup.setItemId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setLayoutData(java.lang.Object)
     */
    public PopupBuilder layoutData(java.lang.Object v0) {
        popup.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setPagePosition(int, int)
     */
    public PopupBuilder pagePosition(int v0, int v1) {
        popup.setPagePosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setPixelSize(int, int)
     */
    public PopupBuilder pixelSize(int v0, int v1) {
        popup.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setPosition(int, int)
     */
    public PopupBuilder position(int v0, int v1) {
        popup.setPosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setResize(boolean)
     */
    public PopupBuilder resize(boolean v0) {
        popup.setResize(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setShadow(boolean)
     */
    public PopupBuilder shadow(boolean v0) {
        popup.setShadow(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setShadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition)
     */
    public PopupBuilder shadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition v0) {
        popup.setShadowPosition(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setSize(java.lang.String, java.lang.String)
     */
    public PopupBuilder size(java.lang.String v0, java.lang.String v1) {
        popup.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setStateId(java.lang.String)
     */
    public PopupBuilder stateId(java.lang.String v0) {
        popup.setStateId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setStateful(boolean)
     */
    public PopupBuilder stateful(boolean v0) {
        popup.setStateful(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setStyleDependentName(java.lang.String, boolean)
     */
    public PopupBuilder styleDependentName(java.lang.String v0, boolean v1) {
        popup.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setStyleName(java.lang.String)
     */
    public PopupBuilder styleName(java.lang.String v0) {
        popup.setStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setStyleName(java.lang.String, boolean)
     */
    public PopupBuilder styleName(java.lang.String v0, boolean v1) {
        popup.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setStylePrimaryName(java.lang.String)
     */
    public PopupBuilder stylePrimaryName(java.lang.String v0) {
        popup.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setTabIndex(int)
     */
    public PopupBuilder tabIndex(int v0) {
        popup.setTabIndex(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setTitle(java.lang.String)
     */
    public PopupBuilder title(java.lang.String v0) {
        popup.setTitle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setToolTip(java.lang.String)
     */
    public PopupBuilder toolTip(java.lang.String v0) {
        popup.setToolTip(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setToolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig)
     */
    public PopupBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        popup.setToolTipConfig(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setVisible(boolean)
     */
    public PopupBuilder visible(boolean v0) {
        popup.setVisible(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setWidget(com.google.gwt.user.client.ui.IsWidget)
     */
    public PopupBuilder widget(com.google.gwt.user.client.ui.IsWidget v0) {
        popup.setWidget(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setWidget(com.google.gwt.user.client.ui.Widget)
     */
    public PopupBuilder widget(com.google.gwt.user.client.ui.Widget v0) {
        popup.setWidget(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setWidth(int)
     */
    public PopupBuilder width(int v0) {
        popup.setWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setWidth(java.lang.String)
     */
    public PopupBuilder width(java.lang.String v0) {
        popup.setWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setXOffset(int)
     */
    public PopupBuilder xOffset(int v0) {
        popup.setXOffset(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.Popup#setYOffset(int)
     */
    public PopupBuilder yOffset(int v0) {
        popup.setYOffset(v0);
        return this;
    }
}
