package biz.freshcode.learn.gwt2.common.client.builder.gwt;

import com.google.gwt.user.client.ui.HorizontalPanel;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.google.gwt.user.client.ui.HorizontalPanel
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt2.common.client.builder.BeanBuilder(HorizontalPanel.class)
public class HorizontalPanelBuilder extends biz.freshcode.learn.gwt2.common.client.builder.Construct.Parent<HorizontalPanelBuilder> {
    public final HorizontalPanel horizontalPanel;

    public HorizontalPanelBuilder(HorizontalPanel v) {
        horizontalPanel = v;
    }

    public HorizontalPanelBuilder() {
        this(new HorizontalPanel());
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#add(com.google.gwt.user.client.ui.Widget)
     */
    public HorizontalPanelBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        horizontalPanel.add(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#add(com.google.gwt.user.client.ui.IsWidget)
     */
    public HorizontalPanelBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        horizontalPanel.add(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#addStyleDependentName(java.lang.String)
     */
    public HorizontalPanelBuilder addStyleDependentName(java.lang.String v0) {
        horizontalPanel.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#addStyleName(java.lang.String)
     */
    public HorizontalPanelBuilder addStyleName(java.lang.String v0) {
        horizontalPanel.addStyleName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setBorderWidth(int)
     */
    public HorizontalPanelBuilder borderWidth(int v0) {
        horizontalPanel.setBorderWidth(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setCellHeight(com.google.gwt.user.client.ui.Widget, java.lang.String)
     */
    public HorizontalPanelBuilder cellHeight(com.google.gwt.user.client.ui.Widget v0, java.lang.String v1) {
        horizontalPanel.setCellHeight(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setCellHeight(com.google.gwt.user.client.ui.IsWidget, java.lang.String)
     */
    public HorizontalPanelBuilder cellHeight(com.google.gwt.user.client.ui.IsWidget v0, java.lang.String v1) {
        horizontalPanel.setCellHeight(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setCellHorizontalAlignment(com.google.gwt.user.client.ui.Widget, com.google.gwt.user.client.ui.HasHorizontalAlignment.HorizontalAlignmentConstant)
     */
    public HorizontalPanelBuilder cellHorizontalAlignment(com.google.gwt.user.client.ui.Widget v0, com.google.gwt.user.client.ui.HasHorizontalAlignment.HorizontalAlignmentConstant v1) {
        horizontalPanel.setCellHorizontalAlignment(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setCellHorizontalAlignment(com.google.gwt.user.client.ui.IsWidget, com.google.gwt.user.client.ui.HasHorizontalAlignment.HorizontalAlignmentConstant)
     */
    public HorizontalPanelBuilder cellHorizontalAlignment(com.google.gwt.user.client.ui.IsWidget v0, com.google.gwt.user.client.ui.HasHorizontalAlignment.HorizontalAlignmentConstant v1) {
        horizontalPanel.setCellHorizontalAlignment(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setCellVerticalAlignment(com.google.gwt.user.client.ui.Widget, com.google.gwt.user.client.ui.HasVerticalAlignment.VerticalAlignmentConstant)
     */
    public HorizontalPanelBuilder cellVerticalAlignment(com.google.gwt.user.client.ui.Widget v0, com.google.gwt.user.client.ui.HasVerticalAlignment.VerticalAlignmentConstant v1) {
        horizontalPanel.setCellVerticalAlignment(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setCellVerticalAlignment(com.google.gwt.user.client.ui.IsWidget, com.google.gwt.user.client.ui.HasVerticalAlignment.VerticalAlignmentConstant)
     */
    public HorizontalPanelBuilder cellVerticalAlignment(com.google.gwt.user.client.ui.IsWidget v0, com.google.gwt.user.client.ui.HasVerticalAlignment.VerticalAlignmentConstant v1) {
        horizontalPanel.setCellVerticalAlignment(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setCellWidth(com.google.gwt.user.client.ui.Widget, java.lang.String)
     */
    public HorizontalPanelBuilder cellWidth(com.google.gwt.user.client.ui.Widget v0, java.lang.String v1) {
        horizontalPanel.setCellWidth(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setCellWidth(com.google.gwt.user.client.ui.IsWidget, java.lang.String)
     */
    public HorizontalPanelBuilder cellWidth(com.google.gwt.user.client.ui.IsWidget v0, java.lang.String v1) {
        horizontalPanel.setCellWidth(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setHeight(java.lang.String)
     */
    public HorizontalPanelBuilder height(java.lang.String v0) {
        horizontalPanel.setHeight(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setHorizontalAlignment(com.google.gwt.user.client.ui.HasHorizontalAlignment.HorizontalAlignmentConstant)
     */
    public HorizontalPanelBuilder horizontalAlignment(com.google.gwt.user.client.ui.HasHorizontalAlignment.HorizontalAlignmentConstant v0) {
        horizontalPanel.setHorizontalAlignment(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setLayoutData(java.lang.Object)
     */
    public HorizontalPanelBuilder layoutData(java.lang.Object v0) {
        horizontalPanel.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setPixelSize(int, int)
     */
    public HorizontalPanelBuilder pixelSize(int v0, int v1) {
        horizontalPanel.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setSize(java.lang.String, java.lang.String)
     */
    public HorizontalPanelBuilder size(java.lang.String v0, java.lang.String v1) {
        horizontalPanel.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setSpacing(int)
     */
    public HorizontalPanelBuilder spacing(int v0) {
        horizontalPanel.setSpacing(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setStyleDependentName(java.lang.String, boolean)
     */
    public HorizontalPanelBuilder styleDependentName(java.lang.String v0, boolean v1) {
        horizontalPanel.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setStyleName(java.lang.String)
     */
    public HorizontalPanelBuilder styleName(java.lang.String v0) {
        horizontalPanel.setStyleName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setStyleName(java.lang.String, boolean)
     */
    public HorizontalPanelBuilder styleName(java.lang.String v0, boolean v1) {
        horizontalPanel.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setStylePrimaryName(java.lang.String)
     */
    public HorizontalPanelBuilder stylePrimaryName(java.lang.String v0) {
        horizontalPanel.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setTitle(java.lang.String)
     */
    public HorizontalPanelBuilder title(java.lang.String v0) {
        horizontalPanel.setTitle(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setVerticalAlignment(com.google.gwt.user.client.ui.HasVerticalAlignment.VerticalAlignmentConstant)
     */
    public HorizontalPanelBuilder verticalAlignment(com.google.gwt.user.client.ui.HasVerticalAlignment.VerticalAlignmentConstant v0) {
        horizontalPanel.setVerticalAlignment(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setVisible(boolean)
     */
    public HorizontalPanelBuilder visible(boolean v0) {
        horizontalPanel.setVisible(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.HorizontalPanel#setWidth(java.lang.String)
     */
    public HorizontalPanelBuilder width(java.lang.String v0) {
        horizontalPanel.setWidth(v0);
        return this;
    }
}
