package biz.freshcode.learn.gwt2.common.client.builder.gwt;

import com.google.gwt.user.client.ui.MenuItem;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.google.gwt.user.client.ui.MenuItem
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt2.common.client.builder.BeanBuilder(MenuItem.class)
public class MenuItemBuilder extends biz.freshcode.learn.gwt2.common.client.builder.Construct.Parent<MenuItemBuilder> {
    public final MenuItem menuItem;

    public MenuItemBuilder(MenuItem v) {
        menuItem = v;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#MenuItem(com.google.gwt.safehtml.shared.SafeHtml)
     */
    public MenuItemBuilder(com.google.gwt.safehtml.shared.SafeHtml v0) {
        this(new MenuItem(v0));
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#MenuItem(java.lang.String, com.google.gwt.user.client.ui.MenuBar)
     */
    public MenuItemBuilder(java.lang.String v0, com.google.gwt.user.client.ui.MenuBar v1) {
        this(new MenuItem(v0, v1));
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#MenuItem(java.lang.String, com.google.gwt.core.client.Scheduler.ScheduledCommand)
     */
    public MenuItemBuilder(java.lang.String v0, com.google.gwt.core.client.Scheduler.ScheduledCommand v1) {
        this(new MenuItem(v0, v1));
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#MenuItem(com.google.gwt.safehtml.shared.SafeHtml, com.google.gwt.user.client.ui.MenuBar)
     */
    public MenuItemBuilder(com.google.gwt.safehtml.shared.SafeHtml v0, com.google.gwt.user.client.ui.MenuBar v1) {
        this(new MenuItem(v0, v1));
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#MenuItem(com.google.gwt.safehtml.shared.SafeHtml, com.google.gwt.core.client.Scheduler.ScheduledCommand)
     */
    public MenuItemBuilder(com.google.gwt.safehtml.shared.SafeHtml v0, com.google.gwt.core.client.Scheduler.ScheduledCommand v1) {
        this(new MenuItem(v0, v1));
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#MenuItem(java.lang.String, boolean, com.google.gwt.user.client.ui.MenuBar)
     */
    public MenuItemBuilder(java.lang.String v0, boolean v1, com.google.gwt.user.client.ui.MenuBar v2) {
        this(new MenuItem(v0, v1, v2));
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#MenuItem(java.lang.String, boolean, com.google.gwt.core.client.Scheduler.ScheduledCommand)
     */
    public MenuItemBuilder(java.lang.String v0, boolean v1, com.google.gwt.core.client.Scheduler.ScheduledCommand v2) {
        this(new MenuItem(v0, v1, v2));
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#addStyleDependentName(java.lang.String)
     */
    public MenuItemBuilder addStyleDependentName(java.lang.String v0) {
        menuItem.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#addStyleName(java.lang.String)
     */
    public MenuItemBuilder addStyleName(java.lang.String v0) {
        menuItem.addStyleName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setCommand(com.google.gwt.user.client.Command)
     */
    @SuppressWarnings("deprecation")
    @Deprecated
    public MenuItemBuilder command(com.google.gwt.user.client.Command v0) {
        menuItem.setCommand(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setEnabled(boolean)
     */
    public MenuItemBuilder enabled(boolean v0) {
        menuItem.setEnabled(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setHTML(java.lang.String)
     */
    public MenuItemBuilder hTML(java.lang.String v0) {
        menuItem.setHTML(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setHTML(com.google.gwt.safehtml.shared.SafeHtml)
     */
    public MenuItemBuilder hTML(com.google.gwt.safehtml.shared.SafeHtml v0) {
        menuItem.setHTML(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setHeight(java.lang.String)
     */
    public MenuItemBuilder height(java.lang.String v0) {
        menuItem.setHeight(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setPixelSize(int, int)
     */
    public MenuItemBuilder pixelSize(int v0, int v1) {
        menuItem.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setScheduledCommand(com.google.gwt.core.client.Scheduler.ScheduledCommand)
     */
    public MenuItemBuilder scheduledCommand(com.google.gwt.core.client.Scheduler.ScheduledCommand v0) {
        menuItem.setScheduledCommand(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setSize(java.lang.String, java.lang.String)
     */
    public MenuItemBuilder size(java.lang.String v0, java.lang.String v1) {
        menuItem.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setStyleDependentName(java.lang.String, boolean)
     */
    public MenuItemBuilder styleDependentName(java.lang.String v0, boolean v1) {
        menuItem.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setStyleName(java.lang.String)
     */
    public MenuItemBuilder styleName(java.lang.String v0) {
        menuItem.setStyleName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setStyleName(java.lang.String, boolean)
     */
    public MenuItemBuilder styleName(java.lang.String v0, boolean v1) {
        menuItem.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setStylePrimaryName(java.lang.String)
     */
    public MenuItemBuilder stylePrimaryName(java.lang.String v0) {
        menuItem.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setSubMenu(com.google.gwt.user.client.ui.MenuBar)
     */
    public MenuItemBuilder subMenu(com.google.gwt.user.client.ui.MenuBar v0) {
        menuItem.setSubMenu(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setText(java.lang.String)
     */
    public MenuItemBuilder text(java.lang.String v0) {
        menuItem.setText(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setTitle(java.lang.String)
     */
    public MenuItemBuilder title(java.lang.String v0) {
        menuItem.setTitle(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setVisible(boolean)
     */
    public MenuItemBuilder visible(boolean v0) {
        menuItem.setVisible(v0);
        return this;
    }

    /**
     * @see com.google.gwt.user.client.ui.MenuItem#setWidth(java.lang.String)
     */
    public MenuItemBuilder width(java.lang.String v0) {
        menuItem.setWidth(v0);
        return this;
    }
}
