package biz.freshcode.learn.gwt.client.builder.gxt.button;

import com.sencha.gxt.widget.core.client.button.TextButton;

/**
 * Generated by BeanBuilderGenerator
 *
 * @see com.sencha.gxt.widget.core.client.button.TextButton
 */
@SuppressWarnings("UnusedDeclaration")
@biz.freshcode.learn.gwt.client.builder.BeanBuilder(TextButton.class)
public class TextButtonBuilder extends biz.freshcode.learn.gwt.client.builder.Construct.Parent<TextButtonBuilder> {
    public final TextButton textButton;

    public TextButtonBuilder(TextButton v) {
        textButton = v;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#TextButton(com.sencha.gxt.cell.core.client.TextButtonCell)
     */
    public TextButtonBuilder(com.sencha.gxt.cell.core.client.TextButtonCell v0) {
        this(new TextButton(v0));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#TextButton(java.lang.String, com.google.gwt.resources.client.ImageResource)
     */
    public TextButtonBuilder(java.lang.String v0, com.google.gwt.resources.client.ImageResource v1) {
        this(new TextButton(v0, v1));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#TextButton(java.lang.String, com.sencha.gxt.widget.core.client.event.SelectEvent.SelectHandler)
     */
    public TextButtonBuilder(java.lang.String v0, com.sencha.gxt.widget.core.client.event.SelectEvent.SelectHandler v1) {
        this(new TextButton(v0, v1));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#TextButton(com.sencha.gxt.cell.core.client.TextButtonCell, java.lang.String)
     */
    public TextButtonBuilder(com.sencha.gxt.cell.core.client.TextButtonCell v0, java.lang.String v1) {
        this(new TextButton(v0, v1));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#TextButton(java.lang.String)
     */
    public TextButtonBuilder(java.lang.String v0) {
        this(new TextButton(v0));
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#TextButton()
     */
    public TextButtonBuilder() {
        this(new TextButton());
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#addStyleDependentName(java.lang.String)
     */
    public TextButtonBuilder addStyleDependentName(java.lang.String v0) {
        textButton.addStyleDependentName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#addStyleName(java.lang.String)
     */
    public TextButtonBuilder addStyleName(java.lang.String v0) {
        textButton.addStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#addStyleOnOver(com.google.gwt.dom.client.Element, java.lang.String)
     */
    public TextButtonBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        textButton.addStyleOnOver(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setAllowTextSelection(boolean)
     */
    public TextButtonBuilder allowTextSelection(boolean v0) {
        textButton.setAllowTextSelection(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setArrowAlign(com.sencha.gxt.cell.core.client.ButtonCell.ButtonArrowAlign)
     */
    public TextButtonBuilder arrowAlign(com.sencha.gxt.cell.core.client.ButtonCell.ButtonArrowAlign v0) {
        textButton.setArrowAlign(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setBorders(boolean)
     */
    public TextButtonBuilder borders(boolean v0) {
        textButton.setBorders(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setBounds(com.sencha.gxt.core.client.util.Rectangle)
     */
    public TextButtonBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        textButton.setBounds(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setBounds(int, int, int, int)
     */
    public TextButtonBuilder bounds(int v0, int v1, int v2, int v3) {
        textButton.setBounds(v0, v1, v2, v3);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setContextMenu(com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public TextButtonBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        textButton.setContextMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setData(java.lang.String, java.lang.Object)
     */
    public TextButtonBuilder data(java.lang.String v0, java.lang.Object v1) {
        textButton.setData(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setDeferHeight(boolean)
     */
    public TextButtonBuilder deferHeight(boolean v0) {
        textButton.setDeferHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setEnabled(boolean)
     */
    public TextButtonBuilder enabled(boolean v0) {
        textButton.setEnabled(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setHTML(com.google.gwt.safehtml.shared.SafeHtml)
     */
    public TextButtonBuilder hTML(com.google.gwt.safehtml.shared.SafeHtml v0) {
        textButton.setHTML(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setHTML(java.lang.String)
     */
    public TextButtonBuilder hTML(java.lang.String v0) {
        textButton.setHTML(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setHeight(int)
     */
    public TextButtonBuilder height(int v0) {
        textButton.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setHeight(java.lang.String)
     */
    public TextButtonBuilder height(java.lang.String v0) {
        textButton.setHeight(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setHideMode(com.sencha.gxt.core.client.Style.HideMode)
     */
    public TextButtonBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        textButton.setHideMode(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setIcon(com.google.gwt.resources.client.ImageResource)
     */
    public TextButtonBuilder icon(com.google.gwt.resources.client.ImageResource v0) {
        textButton.setIcon(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setIconAlign(com.sencha.gxt.cell.core.client.ButtonCell.IconAlign)
     */
    public TextButtonBuilder iconAlign(com.sencha.gxt.cell.core.client.ButtonCell.IconAlign v0) {
        textButton.setIconAlign(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setId(java.lang.String)
     */
    public TextButtonBuilder id(java.lang.String v0) {
        textButton.setId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setItemId(java.lang.String)
     */
    public TextButtonBuilder itemId(java.lang.String v0) {
        textButton.setItemId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setLayoutData(java.lang.Object)
     */
    public TextButtonBuilder layoutData(java.lang.Object v0) {
        textButton.setLayoutData(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setMenu(com.sencha.gxt.widget.core.client.menu.Menu)
     */
    public TextButtonBuilder menu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        textButton.setMenu(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setMenuAlign(com.sencha.gxt.core.client.Style.AnchorAlignment)
     */
    public TextButtonBuilder menuAlign(com.sencha.gxt.core.client.Style.AnchorAlignment v0) {
        textButton.setMenuAlign(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setMinWidth(int)
     */
    public TextButtonBuilder minWidth(int v0) {
        textButton.setMinWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setMouseEvents(boolean)
     */
    public TextButtonBuilder mouseEvents(boolean v0) {
        textButton.setMouseEvents(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setPagePosition(int, int)
     */
    public TextButtonBuilder pagePosition(int v0, int v1) {
        textButton.setPagePosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setPixelSize(int, int)
     */
    public TextButtonBuilder pixelSize(int v0, int v1) {
        textButton.setPixelSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setPosition(int, int)
     */
    public TextButtonBuilder position(int v0, int v1) {
        textButton.setPosition(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setScale(com.sencha.gxt.cell.core.client.ButtonCell.ButtonScale)
     */
    public TextButtonBuilder scale(com.sencha.gxt.cell.core.client.ButtonCell.ButtonScale v0) {
        textButton.setScale(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setShadow(boolean)
     */
    public TextButtonBuilder shadow(boolean v0) {
        textButton.setShadow(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setShadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition)
     */
    public TextButtonBuilder shadowPosition(com.sencha.gxt.core.client.dom.Layer.ShadowPosition v0) {
        textButton.setShadowPosition(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setSize(java.lang.String, java.lang.String)
     */
    public TextButtonBuilder size(java.lang.String v0, java.lang.String v1) {
        textButton.setSize(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setStateId(java.lang.String)
     */
    public TextButtonBuilder stateId(java.lang.String v0) {
        textButton.setStateId(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setStateful(boolean)
     */
    public TextButtonBuilder stateful(boolean v0) {
        textButton.setStateful(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setStyleDependentName(java.lang.String, boolean)
     */
    public TextButtonBuilder styleDependentName(java.lang.String v0, boolean v1) {
        textButton.setStyleDependentName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setStyleName(java.lang.String)
     */
    public TextButtonBuilder styleName(java.lang.String v0) {
        textButton.setStyleName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setStyleName(java.lang.String, boolean)
     */
    public TextButtonBuilder styleName(java.lang.String v0, boolean v1) {
        textButton.setStyleName(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setStylePrimaryName(java.lang.String)
     */
    public TextButtonBuilder stylePrimaryName(java.lang.String v0) {
        textButton.setStylePrimaryName(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setTabIndex(int)
     */
    public TextButtonBuilder tabIndex(int v0) {
        textButton.setTabIndex(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setText(java.lang.String)
     */
    public TextButtonBuilder text(java.lang.String v0) {
        textButton.setText(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setTitle(java.lang.String)
     */
    public TextButtonBuilder title(java.lang.String v0) {
        textButton.setTitle(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setToolTip(java.lang.String)
     */
    public TextButtonBuilder toolTip(java.lang.String v0) {
        textButton.setToolTip(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setToolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig)
     */
    public TextButtonBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        textButton.setToolTipConfig(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setValue(Object)
     */
    public TextButtonBuilder value(String v0) {
        textButton.setValue(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setValue(Object, boolean)
     */
    public TextButtonBuilder value(String v0, boolean v1) {
        textButton.setValue(v0, v1);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setValue(Object, boolean, boolean)
     */
    public TextButtonBuilder value(String v0, boolean v1, boolean v2) {
        textButton.setValue(v0, v1, v2);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setVisible(boolean)
     */
    public TextButtonBuilder visible(boolean v0) {
        textButton.setVisible(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setWidth(int)
     */
    public TextButtonBuilder width(int v0) {
        textButton.setWidth(v0);
        return this;
    }

    /**
     * @see com.sencha.gxt.widget.core.client.button.TextButton#setWidth(java.lang.String)
     */
    public TextButtonBuilder width(java.lang.String v0) {
        textButton.setWidth(v0);
        return this;
    }
}
