package biz.freshcode.learn.gwt.client.uispike.builder.container;

import com.google.gwt.user.client.ui.AbsolutePanel;

// Generated by BeanBuilderGenerator
@biz.freshcode.learn.gwt.client.uispike.builder.BeanBuilder(AbsolutePanel.class)
public class AbsolutePanelBuilder {
    public final AbsolutePanel absolutePanel;

    public AbsolutePanelBuilder() {
        this(new AbsolutePanel());
    }

    public AbsolutePanelBuilder(AbsolutePanel v) {
        absolutePanel = v;
    }

    public AbsolutePanelBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        absolutePanel.add(v0);
        return this;
    }

    public AbsolutePanelBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        absolutePanel.add(v0);
        return this;
    }

    public AbsolutePanelBuilder add(com.google.gwt.user.client.ui.Widget v0, int v1, int v2) {
        absolutePanel.add(v0, v1, v2);
        return this;
    }

    public AbsolutePanelBuilder add(com.google.gwt.user.client.ui.IsWidget v0, int v1, int v2) {
        absolutePanel.add(v0, v1, v2);
        return this;
    }

    public AbsolutePanelBuilder addStyleDependentName(java.lang.String v0) {
        absolutePanel.addStyleDependentName(v0);
        return this;
    }

    public AbsolutePanelBuilder addStyleName(java.lang.String v0) {
        absolutePanel.addStyleName(v0);
        return this;
    }

    public AbsolutePanelBuilder height(java.lang.String v0) {
        absolutePanel.setHeight(v0);
        return this;
    }

    public AbsolutePanelBuilder layoutData(java.lang.Object v0) {
        absolutePanel.setLayoutData(v0);
        return this;
    }

    public AbsolutePanelBuilder pixelSize(int v0, int v1) {
        absolutePanel.setPixelSize(v0, v1);
        return this;
    }

    public AbsolutePanelBuilder size(java.lang.String v0, java.lang.String v1) {
        absolutePanel.setSize(v0, v1);
        return this;
    }

    public AbsolutePanelBuilder styleDependentName(java.lang.String v0, boolean v1) {
        absolutePanel.setStyleDependentName(v0, v1);
        return this;
    }

    public AbsolutePanelBuilder styleName(java.lang.String v0) {
        absolutePanel.setStyleName(v0);
        return this;
    }

    public AbsolutePanelBuilder styleName(java.lang.String v0, boolean v1) {
        absolutePanel.setStyleName(v0, v1);
        return this;
    }

    public AbsolutePanelBuilder stylePrimaryName(java.lang.String v0) {
        absolutePanel.setStylePrimaryName(v0);
        return this;
    }

    public AbsolutePanelBuilder title(java.lang.String v0) {
        absolutePanel.setTitle(v0);
        return this;
    }

    public AbsolutePanelBuilder visible(boolean v0) {
        absolutePanel.setVisible(v0);
        return this;
    }

    public AbsolutePanelBuilder widgetPosition(com.google.gwt.user.client.ui.Widget v0, int v1, int v2) {
        absolutePanel.setWidgetPosition(v0, v1, v2);
        return this;
    }

    public AbsolutePanelBuilder width(java.lang.String v0) {
        absolutePanel.setWidth(v0);
        return this;
    }
}
