package biz.freshcode.learn.gwt.client.uispike.builder.container;


import biz.freshcode.learn.gwt.client.uispike.builder.BeanBuilder;
import com.google.gwt.user.client.ui.DockLayoutPanel;

// Generated by BeanBuilderGenerator
@BeanBuilder(DockLayoutPanel.class)
public class DockLayoutPanelBuilder {
    public final DockLayoutPanel dockLayoutPanel;

    public DockLayoutPanelBuilder(DockLayoutPanel v) {
        dockLayoutPanel = v;
    }

    public DockLayoutPanelBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        dockLayoutPanel.add(v0);
        return this;
    }

    public DockLayoutPanelBuilder addEast(com.google.gwt.user.client.ui.Widget v0, double v1) {
        dockLayoutPanel.addEast(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder addEast(com.google.gwt.user.client.ui.IsWidget v0, double v1) {
        dockLayoutPanel.addEast(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder addLineEnd(com.google.gwt.user.client.ui.Widget v0, double v1) {
        dockLayoutPanel.addLineEnd(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder addLineStart(com.google.gwt.user.client.ui.Widget v0, double v1) {
        dockLayoutPanel.addLineStart(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder addNorth(com.google.gwt.user.client.ui.Widget v0, double v1) {
        dockLayoutPanel.addNorth(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder addNorth(com.google.gwt.user.client.ui.IsWidget v0, double v1) {
        dockLayoutPanel.addNorth(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder addSouth(com.google.gwt.user.client.ui.Widget v0, double v1) {
        dockLayoutPanel.addSouth(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder addSouth(com.google.gwt.user.client.ui.IsWidget v0, double v1) {
        dockLayoutPanel.addSouth(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder addWest(com.google.gwt.user.client.ui.Widget v0, double v1) {
        dockLayoutPanel.addWest(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder addWest(com.google.gwt.user.client.ui.IsWidget v0, double v1) {
        dockLayoutPanel.addWest(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder widgetSize(com.google.gwt.user.client.ui.Widget v0, double v1) {
        dockLayoutPanel.setWidgetSize(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        dockLayoutPanel.add(v0);
        return this;
    }

    public DockLayoutPanelBuilder layoutData(java.lang.Object v0) {
        dockLayoutPanel.setLayoutData(v0);
        return this;
    }

    public DockLayoutPanelBuilder size(java.lang.String v0, java.lang.String v1) {
        dockLayoutPanel.setSize(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder visible(boolean v0) {
        dockLayoutPanel.setVisible(v0);
        return this;
    }

    public DockLayoutPanelBuilder styleName(java.lang.String v0, boolean v1) {
        dockLayoutPanel.setStyleName(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder styleName(java.lang.String v0) {
        dockLayoutPanel.setStyleName(v0);
        return this;
    }

    public DockLayoutPanelBuilder stylePrimaryName(java.lang.String v0) {
        dockLayoutPanel.setStylePrimaryName(v0);
        return this;
    }

    public DockLayoutPanelBuilder addStyleDependentName(java.lang.String v0) {
        dockLayoutPanel.addStyleDependentName(v0);
        return this;
    }

    public DockLayoutPanelBuilder addStyleName(java.lang.String v0) {
        dockLayoutPanel.addStyleName(v0);
        return this;
    }

    public DockLayoutPanelBuilder height(java.lang.String v0) {
        dockLayoutPanel.setHeight(v0);
        return this;
    }

    public DockLayoutPanelBuilder pixelSize(int v0, int v1) {
        dockLayoutPanel.setPixelSize(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder styleDependentName(java.lang.String v0, boolean v1) {
        dockLayoutPanel.setStyleDependentName(v0, v1);
        return this;
    }

    public DockLayoutPanelBuilder title(java.lang.String v0) {
        dockLayoutPanel.setTitle(v0);
        return this;
    }

    public DockLayoutPanelBuilder width(java.lang.String v0) {
        dockLayoutPanel.setWidth(v0);
        return this;
    }
}
