package biz.freshcode.learn.gwt.client.uispike.builder.container;

import com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer;

// Generated by BeanBuilderGenerator
@biz.freshcode.learn.gwt.client.uispike.builder.BeanBuilder(HBoxLayoutContainer.class)
public class HBoxLayoutContainerBuilder {
    public final HBoxLayoutContainer hBoxLayoutContainer;

    public HBoxLayoutContainerBuilder() {
        this(new HBoxLayoutContainer());
    }

    public HBoxLayoutContainerBuilder(HBoxLayoutContainer v) {
        hBoxLayoutContainer = v;
    }

    public HBoxLayoutContainerBuilder add(com.google.gwt.user.client.ui.IsWidget v0) {
        hBoxLayoutContainer.add(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder add(com.google.gwt.user.client.ui.Widget v0) {
        hBoxLayoutContainer.add(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder add(com.google.gwt.user.client.ui.IsWidget v0, com.sencha.gxt.widget.core.client.container.BoxLayoutContainer.BoxLayoutData v1) {
        hBoxLayoutContainer.add(v0, v1);
        return this;
    }

    public HBoxLayoutContainerBuilder addStyleDependentName(java.lang.String v0) {
        hBoxLayoutContainer.addStyleDependentName(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder addStyleName(java.lang.String v0) {
        hBoxLayoutContainer.addStyleName(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder addStyleOnOver(com.google.gwt.dom.client.Element v0, java.lang.String v1) {
        hBoxLayoutContainer.addStyleOnOver(v0, v1);
        return this;
    }

    public HBoxLayoutContainerBuilder adjustForFlexRemainder(boolean v0) {
        hBoxLayoutContainer.setAdjustForFlexRemainder(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder allowTextSelection(boolean v0) {
        hBoxLayoutContainer.setAllowTextSelection(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder borders(boolean v0) {
        hBoxLayoutContainer.setBorders(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder bounds(com.sencha.gxt.core.client.util.Rectangle v0) {
        hBoxLayoutContainer.setBounds(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder bounds(int v0, int v1, int v2, int v3) {
        hBoxLayoutContainer.setBounds(v0, v1, v2, v3);
        return this;
    }

    public HBoxLayoutContainerBuilder contextMenu(com.sencha.gxt.widget.core.client.menu.Menu v0) {
        hBoxLayoutContainer.setContextMenu(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder data(java.lang.String v0, java.lang.Object v1) {
        hBoxLayoutContainer.setData(v0, v1);
        return this;
    }

    public HBoxLayoutContainerBuilder deferHeight(boolean v0) {
        hBoxLayoutContainer.setDeferHeight(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder enableOverflow(boolean v0) {
        hBoxLayoutContainer.setEnableOverflow(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder enabled(boolean v0) {
        hBoxLayoutContainer.setEnabled(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder hBoxLayoutAlign(com.sencha.gxt.widget.core.client.container.HBoxLayoutContainer.HBoxLayoutAlign v0) {
        hBoxLayoutContainer.setHBoxLayoutAlign(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder height(int v0) {
        hBoxLayoutContainer.setHeight(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder height(java.lang.String v0) {
        hBoxLayoutContainer.setHeight(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder hideMode(com.sencha.gxt.core.client.Style.HideMode v0) {
        hBoxLayoutContainer.setHideMode(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder id(java.lang.String v0) {
        hBoxLayoutContainer.setId(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder itemId(java.lang.String v0) {
        hBoxLayoutContainer.setItemId(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder layoutData(java.lang.Object v0) {
        hBoxLayoutContainer.setLayoutData(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder pack(com.sencha.gxt.widget.core.client.container.BoxLayoutContainer.BoxLayoutPack v0) {
        hBoxLayoutContainer.setPack(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder padding(com.sencha.gxt.core.client.util.Padding v0) {
        hBoxLayoutContainer.setPadding(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder pagePosition(int v0, int v1) {
        hBoxLayoutContainer.setPagePosition(v0, v1);
        return this;
    }

    public HBoxLayoutContainerBuilder pixelSize(int v0, int v1) {
        hBoxLayoutContainer.setPixelSize(v0, v1);
        return this;
    }

    public HBoxLayoutContainerBuilder position(int v0, int v1) {
        hBoxLayoutContainer.setPosition(v0, v1);
        return this;
    }

    public HBoxLayoutContainerBuilder scrollOffset(int v0) {
        hBoxLayoutContainer.setScrollOffset(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder shadow(boolean v0) {
        hBoxLayoutContainer.setShadow(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder size(java.lang.String v0, java.lang.String v1) {
        hBoxLayoutContainer.setSize(v0, v1);
        return this;
    }

    public HBoxLayoutContainerBuilder stateId(java.lang.String v0) {
        hBoxLayoutContainer.setStateId(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder stateful(boolean v0) {
        hBoxLayoutContainer.setStateful(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder styleDependentName(java.lang.String v0, boolean v1) {
        hBoxLayoutContainer.setStyleDependentName(v0, v1);
        return this;
    }

    public HBoxLayoutContainerBuilder styleName(java.lang.String v0) {
        hBoxLayoutContainer.setStyleName(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder styleName(java.lang.String v0, boolean v1) {
        hBoxLayoutContainer.setStyleName(v0, v1);
        return this;
    }

    public HBoxLayoutContainerBuilder stylePrimaryName(java.lang.String v0) {
        hBoxLayoutContainer.setStylePrimaryName(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder tabIndex(int v0) {
        hBoxLayoutContainer.setTabIndex(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder title(java.lang.String v0) {
        hBoxLayoutContainer.setTitle(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder toolTip(java.lang.String v0) {
        hBoxLayoutContainer.setToolTip(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder toolTipConfig(com.sencha.gxt.widget.core.client.tips.ToolTipConfig v0) {
        hBoxLayoutContainer.setToolTipConfig(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder visible(boolean v0) {
        hBoxLayoutContainer.setVisible(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder width(int v0) {
        hBoxLayoutContainer.setWidth(v0);
        return this;
    }

    public HBoxLayoutContainerBuilder width(java.lang.String v0) {
        hBoxLayoutContainer.setWidth(v0);
        return this;
    }
}
